import test from 'node:test';
import assert from 'node:assert/strict';
import R from '@dimforge/rapier3d-compat/rapier.es.js';
import {BoatController,integrateHelm} from '../sources/core/boat.js';
import {createIslandColliders,createBoundaryColliders} from '../sources/core/collisions.js';
import {Race,segmentCrossesGate} from '../sources/core/race.js';
import {islands,gates,WORLD_RADIUS,inDockZone} from '../sources/config.js';
await R.init();
function setup(spawn){const world=new R.World({x:0,y:0,z:0});world.timestep=1/60;return {world,boat:new BoatController(R,world,spawn)};}
const full={throttle:1,steer:0,boost:true};
test('30, 60 and 120 FPS render schedules produce the same fixed-step voyage',()=>{
 function simulate(fps){let s={vx:0,vz:0,yaw:0},x=0,z=0,acc=0,ticks=0;for(let f=0;f<fps*12;f++){acc+=1/fps;while(acc+1e-10>=1/60){integrateHelm(s,{throttle:1,steer:ticks>=180&&ticks<360?.5:0,boost:ticks>360},1/60);x+=s.vx/60;z+=s.vz/60;ticks++;acc-=1/60;}}return {x,z,yaw:s.yaw,ticks};}
 const reference=simulate(60);for(const fps of [30,120]){const actual=simulate(fps);assert.equal(actual.ticks,720);assert.ok(Math.hypot(actual.x-reference.x,actual.z-reference.z)<1e-8);assert.ok(Math.abs(actual.yaw-reference.yaw)<1e-8);}
});
test('throttle, drag, braking and reverse stay within requested units/second limits',()=>{let s={vx:0,vz:0,yaw:0};for(let n=0;n<1000;n++)integrateHelm(s,full,1/60);assert.ok(Math.abs(s.vz+24)<1e-6);for(let n=0;n<150;n++)integrateHelm(s,{throttle:-1},1/60);assert.ok(s.vz>0&&s.vz<=4);for(let n=0;n<60;n++)integrateHelm(s,{brake:true},1/60);assert.ok(Math.abs(s.vz)<.01);});
test('all four spawn and dock zones keep a complete boat clear of shore and pier',()=>{for(const i of islands){const {world,boat}=setup({...i.dock,yaw:i.yaw});createIslandColliders(R,world,i);for(let n=0;n<10;n++)world.step();assert.ok(Math.hypot(boat.position.x-i.dock.x,boat.position.z-i.dock.z)<.001,i.id);assert.ok(inDockZone(boat.position,i),i.id);assert.ok(!inDockZone({x:i.x,z:i.z},i));world.free();}});
test('top-speed head-on and oblique shore impacts do not tunnel through the island',()=>{for(const angle of [0,.35,-.35]){const {world,boat}=setup({x:4,z:-32,yaw:Math.PI+angle});createIslandColliders(R,world,{x:0,z:0,rotation:0});let min=Infinity;for(let n=0;n<300;n++){boat.step(full,1/60);world.step();min=Math.min(min,Math.hypot(boat.position.x,boat.position.z));}assert.ok(min>=11.1,`${angle}: ${min}`);world.free();}});
test('top-speed pier impact blocks the hull before it overlaps the deck',()=>{const {world,boat}=setup({x:0,z:32,yaw:0});createIslandColliders(R,world,{x:0,z:0,rotation:0});for(let n=0;n<240;n++){boat.step(full,1/60);world.step();assert.ok(boat.position.z>=17.5);}world.free();});
test('boundary segments block head-on and oblique strikes across segment joins',()=>{for(const angle of [0,.018,.035,.06,1,2]){const {world,boat}=setup({x:Math.cos(angle)*155,z:Math.sin(angle)*155,yaw:-Math.PI/2-angle});createBoundaryColliders(R,world,WORLD_RADIUS);for(let n=0;n<240;n++){boat.step(full,1/60);world.step();assert.ok(Math.hypot(boat.position.x,boat.position.z)<WORLD_RADIUS+2);}world.free();}});
test('reset/teleport zero velocity and use a safe saved heading',()=>{const {world,boat}=setup({x:0,z:0,yaw:0});boat.step(full,1);const snapshot=boat.snapshot();boat.teleport({...islands[1].dock,yaw:islands[1].yaw});assert.equal(boat.speed,0);boat.restore(snapshot);assert.ok(boat.speed>0);boat.teleport({...islands[0].dock,yaw:islands[0].yaw});assert.equal(boat.speed,0);world.free();});
test('fast crossing counts, sideways grazing and reverse crossings do not',()=>{const g={x:0,z:0,nx:1,nz:0,r:10};assert.ok(segmentCrossesGate({x:-100,z:0},{x:100,z:0},g));assert.ok(!segmentCrossesGate({x:11,z:0},{x:9,z:0},g));assert.ok(!segmentCrossesGate({x:100,z:0},{x:-100,z:0},g));assert.ok(!segmentCrossesGate({x:-10,z:11},{x:10,z:11},g));});
test('race enforces gate order and saves only a complete course',()=>{let now=0,finish=0;const course=[0,20].map(x=>({x,z:0,nx:1,nz:0,r:5}));const race=new Race(course,{now:()=>now,onFinish:()=>finish++});race.start();now=3000;race.tick({x:10,z:0},{x:30,z:0});assert.equal(race.index,0);now=4000;race.tick({x:-10,z:0},{x:10,z:0});assert.equal(race.index,1);assert.equal(finish,0);now=5000;race.tick({x:10,z:0},{x:30,z:0});assert.equal(finish,1);assert.equal(race.elapsed,2000);});
test('pause and repeated resume countdown exclude all paused time',()=>{let now=0;const r=new Race(gates,{now:()=>now});r.start();now=3000;r.tick({x:0,z:0},{x:0,z:0});now=4500;r.pause();now=15000;r.resume();now=15500;r.pause();now=17000;r.resume();now=19000;r.tick({x:0,z:0},{x:0,z:0});now=19500;r.tick({x:0,z:0},{x:0,z:0});assert.equal(r.elapsed,2000);assert.equal(r.state,'running');r.cancel();assert.equal(r.best,0);assert.equal(r.active,false);assert.equal(r.beforePause,null);});
test('pausing the initial countdown resumes without prematurely starting the clock',()=>{let now=0;const r=new Race(gates,{now:()=>now});r.start();now=1000;r.pause();now=6000;r.resume();assert.equal(r.deadline,8000);now=7999;r.tick({x:0,z:0},{x:0,z:0});assert.equal(r.state,'countdown');now=8000;r.tick({x:0,z:0},{x:0,z:0});assert.equal(r.elapsed,0);});
