import test from 'node:test';
import assert from 'node:assert/strict';
import {Inputs} from '../sources/core/inputs.js';
function environment(){const listeners={},nodes=new Map();const node=()=>({style:{},events:{},addEventListener(k,f){this.events[k]=f},setPointerCapture(){},getBoundingClientRect(){return {x:0,y:0,width:100,height:100}}});nodes.set('#joystick',node());nodes.set('#joystick-knob',node());globalThis.window={addEventListener(k,f){listeners[k]=f}};globalThis.document={querySelector:k=>nodes.get(k),querySelectorAll:()=>[]};const input=new Inputs();function key(code,{repeat=false,button=false}={}){listeners.keydown({code,repeat,preventDefault(){},target:{closest:s=>button&&s==='button,a'}})}return {input,listeners,nodes,key};}
test('keyboard steering works while a returned navigation button has focus',()=>{const {input,key}=environment();key('KeyW',{button:true});assert.equal(input.read().throttle,1);});
test('lost keyup after blur does not block the next fresh keydown',()=>{const {input,key,listeners}=environment();key('KeyW');listeners.blur();key('KeyW');assert.equal(input.read().throttle,1);});
test('held keyboard inputs cannot reactivate from a repeat after pausing',()=>{const {input,key}=environment();key('KeyW');input.setEnabled(false);input.setEnabled(true);key('KeyW',{repeat:true});assert.equal(input.read().throttle,0);input.setEnabled(false);key('KeyS');input.setEnabled(true);key('KeyS',{repeat:true});assert.equal(input.read().throttle,0);key('KeyW');assert.equal(input.read().throttle,1);});
test('canceled touches and held pointers cannot reactivate after a panel closes',()=>{const {input,nodes}=environment(),pad=nodes.get('#joystick');const event={clientX:50,clientY:0,pointerId:1,preventDefault(){}};pad.events.pointerdown(event);assert.equal(input.read().throttle,1);input.setEnabled(false);input.setEnabled(true);pad.events.pointermove(event);assert.equal(input.read().throttle,0);pad.events.pointerdown(event);pad.events.pointercancel(event);assert.equal(input.read().throttle,0);});
test('phone joystick heading accounts for the camera orientation',()=>{const {input,nodes}=environment();nodes.get('#joystick').events.pointerdown({clientX:50,clientY:0,pointerId:1,preventDefault(){}});const yaw=Math.atan2(34,61);assert.equal(input.read(yaw,yaw).steer,0);assert.equal(input.read(yaw,yaw).throttle,1);});
