import test from 'node:test';
import assert from 'node:assert/strict';
import {Scene,Group} from 'three';
import R from '@dimforge/rapier3d-compat/rapier.es.js';
import {AmbientFleet} from '../sources/world/fleet.js';
import {FLEET_ROUTES,routePoint,routeYaw,waterClear} from '../sources/world/water-space.js';
import {HABITATS,SHOALS} from '../sources/world/marine.js';
import {createIslandColliders} from '../sources/core/collisions.js';
import {islands,reefGroups,toWorld} from '../sources/config.js';
import {inDockZone,DockInteraction,pointInPolygon} from '../sources/core/dock.js';
await R.init();
const idlePlayer={position:{x:0,z:67},velocity:{x:0,z:0},yaw:0};
async function fleetFixture(){const world=new R.World({x:0,y:0,z:0});world.timestep=1/60;for(const i of islands)createIslandColliders(R,world,i);for(const r of reefGroups)world.createCollider(R.ColliderDesc.cylinder(2,r.r).setTranslation(r.x,0,r.z));const sounds=[];const fleet=new AmbientFleet(new Scene(),R,world,{quality:'high',reduced:false},{loadAsync:async()=>({scene:new Group()})},(kind,p)=>sounds.push({kind,p:{...p}}));await fleet.load();return{world,fleet,sounds};}
function hullClear(item,options={activities:true,docks:true}){const r=item.route,p=item.body.translation(),q=item.body.rotation(),yaw=2*Math.atan2(q.y,q.w);for(const along of [-.5,0,.5])if(!waterClear({x:p.x-Math.sin(yaw)*r.length*along,z:p.z-Math.cos(yaw)*r.length*along},r.width/2,options))return false;return true;}
test('actual vessel movement remains in protected water after two minutes of fixed steps',async()=>{const {world,fleet}=await fleetFixture();try{const distance=new Map(fleet.items.map(i=>[i.route.id,0]));for(let n=0;n<7200;n++){const previous=fleet.items.map(i=>i.body.translation());fleet.beforeStep(1/60,idlePlayer);world.step();for(const [k,i]of fleet.items.entries()){const p=i.body.translation();distance.set(i.route.id,distance.get(i.route.id)+Math.hypot(p.x-previous[k].x,p.z-previous[k].z));if(n%10===0)assert.ok(hullClear(i),`${i.route.id} unsafe actual pose at frame ${n}`);}}for(const [id,d]of distance)assert.ok(d>60,`${id} unexpectedly stuck`);}finally{world.free();}});
test('a gently displaced cargo vessel returns instead of holding at shore clearance forever',async()=>{const {world,fleet}=await fleetFixture();try{const i=fleet.items.find(i=>i.route.id==='cargo');i.body.setTranslation({x:-89,y:0,z:-40},true);i.body.setLinvel({x:0,y:0,z:0},true);for(let n=0;n<600;n++){fleet.beforeStep(1/60,idlePlayer);world.step();}assert.ok(Math.hypot(i.body.translation().x+89,i.body.translation().z+40)>4,'cargo failed to move back toward route');assert.ok(hullClear(i));}finally{world.free();}});
test('a predicted high-speed head-on player approach makes an NPC yield before contact',async()=>{const {world,fleet}=await fleetFixture();try{const i=fleet.items.find(i=>i.route.id==='ferry'),p=i.body.translation(),forward={x:-Math.sin(i.yaw),z:-Math.cos(i.yaw)};fleet.beforeStep(1/60,{position:{x:p.x+forward.x*25,z:p.z+forward.z*25},velocity:{x:-forward.x*18,z:-forward.z*18},yaw:i.yaw+Math.PI});assert.equal(i.state,'yielding');assert.ok(i.holdUntil>fleet.time);}finally{world.free();}});
test('horn obeys player and nearest-vessel cooldowns; travel clears a pending reply',async()=>{const {world,fleet,sounds}=await fleetFixture();try{const i=fleet.items.find(i=>i.route.id==='ferry'),p=i.body.translation();assert.equal(fleet.horn(p),true);assert.equal(fleet.horn(p),false);assert.equal(sounds.filter(e=>e.kind==='horn-reply').length,0);for(let n=0;n<30;n++)fleet.beforeStep(1/60,idlePlayer);assert.equal(sounds.filter(e=>e.kind==='horn-reply').length,1);for(let n=0;n<180;n++)fleet.beforeStep(1/60,idlePlayer);assert.equal(fleet.horn(p),true);assert.equal(i.replyPending,false,'same nearest vessel must stay quiet inside ten seconds');for(let n=0;n<600;n++)fleet.beforeStep(1/60,idlePlayer);assert.equal(fleet.horn(p),true);assert.equal(i.replyPending,true);fleet.onTravel();for(let n=0;n<30;n++)fleet.beforeStep(1/60,idlePlayer);assert.equal(i.replyPending,false);assert.equal(sounds.filter(e=>e.kind==='horn-reply').length,1);}finally{world.free();}});
test('an intervening island wall blocks E even when the center is within five units of the pier',()=>{const i={x:0,z:0,rotation:0,pier:{width:3,startZ:7.9,endZ:15.8},shore:[[-3.5,3],[-2.5,3],[-2.5,22],[-3.5,22]]};assert.equal(inDockZone({x:-5,z:12},i),false);});
test('30, 60 and 120 FPS render schedules preserve the same fixed-step fleet voyage',async()=>{const results=[];for(const fps of [30,60,120]){const {world,fleet}=await fleetFixture();try{let accumulator=0;for(let n=0;n<fps*10;n++){accumulator+=1/fps;while(accumulator+1e-10>=1/60){fleet.beforeStep(1/60,idlePlayer);world.step();accumulator-=1/60;}fleet.update(Math.max(0,accumulator*60),idlePlayer.position,fleet.time);}results.push(fleet.status());}finally{world.free();}}for(let r=1;r<results.length;r++)for(let i=0;i<6;i++){const a=results[0][i],b=results[r][i];assert.ok(Math.hypot(a.position.x-b.position.x,a.position.z-b.position.z)<.01);assert.ok(Math.abs(a.speed-b.speed)<.01);}});
