import test from 'node:test';
import assert from 'node:assert/strict';
import R from '@dimforge/rapier3d-compat/rapier.es.js';
import {CharacterController,IslandWalkWorld,SEA_GROUP,localToWorld} from '../sources/core/character.js';
import {PlayerController,BoardingController} from '../sources/core/player.js';
import {BoatController} from '../sources/core/boat.js';
import {Game} from '../sources/game.js';
import {ChallengeManager} from '../sources/core/challenges.js';
await R.init();
function fixture(){const world=new R.World({x:0,y:0,z:0});world.timestep=1/60;const island={x:0,z:0,rotation:0,shore:[[-30,-30],[30,-30],[30,30],[-30,30]]};const layout={groundY:.85,surfaces:[],obstacles:[{x:0,z:-8,width:20,depth:1,height:4}],stations:[]};const walk=new IslandWalkWorld(R,world,island,layout);world.createCollider(R.ColliderDesc.cuboid(30,3,30).setCollisionGroups(SEA_GROUP));const c=new CharacterController(R,world);c.teleport({x:0,y:.85,z:0},walk);c.enable(true);world.step();return{world,c,walk};}
test('actual character ignores sea high floor, stays grounded, collides with wall and exits cleanly',()=>{const {world,c}=fixture();try{for(let n=0;n<360;n++){c.step({x:0,z:-1},1/60);world.step();c.afterStep();}assert.ok(Math.abs(c.position.y-.85)<.04,JSON.stringify(c.position));assert.ok(c.position.z>-7.3,JSON.stringify(c.position));assert.ok(c.speed<.05,'wall stops movement');for(let n=0;n<60;n++){c.step({x:0,z:1},1/60);world.step();c.afterStep();}assert.ok(c.position.z>-5.2);}finally{world.free();}});
test('character wall and grounded movement preserve 30/60/120 schedule results',()=>{const positions=[];for(const fps of [30,60,120]){const {world,c}=fixture();try{let acc=0;for(let i=0;i<fps*3;i++){acc+=1/fps;while(acc+1e-9>=1/60){c.step({x:1,z:1,run:true},1/60);world.step();c.afterStep();acc-=1/60;}}positions.push(c.position);}finally{world.free();}}for(const p of positions)assert.ok(Math.hypot(p.x-positions[0].x,p.z-positions[0].z)<.01);assert.ok(Math.abs(Math.hypot(positions[0].x,positions[0].z)-12)<12*.05);});
test('parked boat withstands force and returns to dynamic driving',()=>{const world=new R.World({x:0,y:0,z:0}),boat=new BoatController(R,world,{x:3,z:4});try{boat.park(true);boat.body.addForce({x:1000,y:0,z:1000},true);for(let i=0;i<60;i++)world.step();assert.equal(boat.position.x,3);assert.equal(boat.position.z,4);boat.park(false);for(let i=0;i<60;i++){boat.step({throttle:1},1/60);world.step();}assert.ok(boat.position.z<3);}finally{world.free();}});
test('cancel pending prepare ignores its old completion and allows a new landing',async()=>{let resolve,commits=0;const char={enable(){},seated:false};const player=new PlayerController({hold(){}},char);const boarding=new BoardingController(player,{prepare:()=>new Promise(r=>resolve=r),select:()=>({}),onCommit:()=>commits++,onError:e=>{throw e;}});const first=boarding.disembark({id:'harbor'});boarding.cancel();resolve({});assert.equal(await first,false);player.tick(1);assert.equal(commits,0);assert.equal(player.mode,'sailing');assert.equal(boarding.pending,false);});
test('panel + hidden nested pause never progresses landing or resumes an old prepare',async()=>{let count=0;const player=new PlayerController({hold(){}},{enable(){}});const board=new BoardingController(player,{prepare:async()=>({}),select:()=>({}),onCommit(){count++;},onError(e){throw e;}});await board.disembark({});player.pauseReasons.add('read');player.pauseReasons.add('hidden');player.tick(1);assert.equal(count,0);player.pauseReasons.delete('read');player.tick(1);assert.equal(count,0);player.pauseReasons.delete('hidden');player.tick(.3);assert.equal(count,1);player.tick(.3);assert.equal(player.mode,'walking');});
function gameFixture(){const g=Object.create(Game.prototype);const boat={position:{x:1,y:.35,z:2},yaw:0,hold(){},park(){},teleport(p){this.position={...p,y:.35}},snapshot(){return{position:this.position,velocity:{x:0,y:0,z:0}}}};const character={enable(){},hold(){},seated:false};const player=new PlayerController(boat,character);Object.assign(g,{player,character,boat,boarding:new BoardingController(player),challenges:new ChallengeManager(),props:{resetCargo(){},resetNear(){},snapshot(){return[];}},mode:'exploring',loaded:new Map(),inputs:{setEnabled(v){this.enabled=v;}},feedback:{clear(){}},safePoint:p=>p,resetCamera(){},updateNearby(){},clearWake(){}});return g;}
test('Travel while hidden must retain background pause',()=>{const g=gameFixture();g.pause('hidden');g.teleport({x:9,z:9});assert.ok(g.player.pauseReasons.has('hidden'),'teleport cleared hidden reason');assert.equal(g.inputs.enabled,false);assert.equal(g.frozen,true);});
test('repeated E cannot create overlapping transitions or duplicate commits',async()=>{let commits=0;const p=new PlayerController({hold(){}},{enable(){}}),b=new BoardingController(p,{prepare:async()=>({}),select:()=>({}),onCommit(){commits++;},onError(e){throw e;}});const first=b.disembark({});assert.equal(await b.disembark({}),false);await first;assert.equal(await b.disembark({}),false);p.tick(.31);assert.equal(p.onLand,true);p.tick(.30);assert.equal(commits,1);assert.equal(p.mode,'walking');assert.equal(b.board(),true);assert.equal(b.board(),false);p.tick(.31);assert.equal(p.onLand,false);p.tick(.3);assert.equal(p.mode,'sailing');assert.equal(commits,2);});
test('cancel before/after midpoint restores the last committed stable actor',async()=>{for(const elapsed of [.2,.4]){const p=new PlayerController({hold(){}},{enable(){}}),b=new BoardingController(p,{prepare:async()=>({}),select:()=>({}),onCommit(){},onError(e){throw e;}});await b.disembark({});p.tick(elapsed);b.cancel();assert.equal(p.mode,elapsed<.3?'sailing':'walking');const epoch=p.transitionEpoch;p.tick(9);assert.equal(p.transitionEpoch,epoch);assert.equal(p.transition,null);}});
test('failed required island loading keeps the player aboard with a retryable error',async()=>{let errors=0;const p=new PlayerController({hold(){}},{enable(){}}),b=new BoardingController(p,{prepare:async()=>{throw new Error('unavailable');},onError(){errors++;}});assert.equal(await b.disembark({}),false);assert.equal(p.mode,'sailing');assert.equal(b.pending,false);assert.equal(errors,1);assert.equal(p.transition,null);});
