import test from 'node:test';
import assert from 'node:assert/strict';
import R from '@dimforge/rapier3d-compat/rapier.es.js';
import {Scene} from 'three';
import {Environment} from '../sources/world/environment.js';
import {PropManager} from '../sources/world/props.js';
import {createIslandColliders} from '../sources/core/collisions.js';
import {BoatController} from '../sources/core/boat.js';
import {ChallengeManager} from '../sources/core/challenges.js';
import {islands,cargoBay,cargoBerths,gates} from '../sources/config.js';
globalThis.document={createElement:()=>({getContext:()=>({beginPath(){},roundRect(){},fill(){},fillText(){}})})};
await R.init();
function setup(){const world=new R.World({x:0,y:0,z:0}),scene=new Scene();world.timestep=1/60;for(const i of islands)createIslandColliders(R,world,i);new Environment(scene,R,world,{});const props=new PropManager(scene,R,world,{settings:{},feedback:{splash(){}}});return{world,props};}
test('all 24 toys spawn free of any other collider, including the revised harbor',()=>{const {world,props}=setup();assert.equal(props.items.length,24);assert.deepEqual(Object.fromEntries(['buoy','crate','ball','duck'].map(k=>[k,props.items.filter(i=>i.kind===k).length])),{buoy:8,crate:8,ball:6,duck:2});world.forEachCollider(c=>{for(const i of props.items)if(c!==i.collider){const hit=c.contactCollider(i.collider,0);assert.ok(!hit||hit.distance>-.005,`${i.id} initial penetration ${hit?.distance}`);}});world.free();});
test('cargo recovery avoids ordinary toys, statics and the full boat; no free candidate stays paused',()=>{const {world,props}=setup(),cargo=props.items.find(i=>i.id==='circle'),ordinary=props.items.find(i=>i.id==='crate-0');props.resetItem(ordinary,cargo.home);cargo.body.setTranslation({x:170,y:.35,z:0},true);assert.equal(props.recoverCargo(cargo,{x:0,z:0}),true);assert.ok(Math.hypot(cargo.body.translation().x-ordinary.body.translation().x,cargo.body.translation().z-ordinary.body.translation().z)>2.8);world.createCollider(R.ColliderDesc.cuboid(30,2,25).setTranslation(cargoBay.x,0,cargoBay.z));assert.equal(props.recoverCargo(cargo,{x:0,z:0}),false);world.free();});
test('a real boat can push a cargo crate into the correct berth and reverse clear',()=>{const {world,props}=setup(),boat=new BoatController(R,world,{x:-30,z:-34,yaw:0}),queue=new R.EventQueue(true);let now=0;const c=new ChallengeManager({berths:cargoBerths,now:()=>now,onEvent:e=>{if(e.type==='delivery')props.deliver(e.id);}});c.start('cargo');now=3000;c.updateClock();for(let n=0;n<500;n++){now+=1000/60;props.beforeStep(boat.position);boat.step({throttle:n<360?.5:0,steer:0,brake:n>=360},1/60);world.step(queue);props.afterStep(queue,boat.collider,boat.position);c.tick({}, {},1/60,props.cargoData());}assert.ok(c.delivered.has('triangle'),'triangle crate must settle fully in berth');assert.equal(props.items.find(i=>i.id==='triangle').collider.isEnabled(),false);const before=boat.position.z;for(let n=0;n<120;n++){boat.step({throttle:-1,steer:0},1/60);world.step(queue);}assert.ok(boat.position.z>before+2);world.free();queue.free();});
test('V2 directed checkpoints reject misses/reverse/repeats and record exactly six ordered gates',()=>{let now=0,finishes=0;const c=new ChallengeManager({gates,now:()=>now,onEvent:e=>finishes+=e.type==='finish'?1:0});c.start('buoy');now=3000;c.updateClock();function cross(g,reverse=false){const a={x:g.x-g.nx*50,z:g.z-g.nz*50},b={x:g.x+g.nx*50,z:g.z+g.nz*50};now+=1000;c.tick(reverse?b:a,reverse?a:b);}cross(gates[1]);assert.equal(c.index,0);cross(gates[0],true);assert.equal(c.index,0);cross(gates[0]);cross(gates[0]);assert.equal(c.index,1);gates.slice(1).forEach(g=>cross(g));assert.equal(finishes,1);assert.equal(c.state,'finished');});
