import { Events } from './Events.js';
// Action/event separation follows Bruno Simon's folio-2025 input architecture.
export class Inputs{
 constructor(){this.events=new Events();this.keys=new Set();this.blocked=new Set();this.touch={active:false,x:0,y:0};this.holds=new Set();this.enabled=true;window.addEventListener('keydown',e=>{const k=e.code;if(e.repeat&&(this.blocked.has(k)||!this.keys.has(k)))return;if(!e.repeat)this.blocked.delete(k);if(e.target.closest('dialog,input,select,textarea,[contenteditable=true]')||!this.enabled){this.blocked.add(k);return;}if(['Enter','Space'].includes(k)&&e.target.closest('button,a'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(k))e.preventDefault();this.keys.add(k);if(!e.repeat)this.events.trigger('action',[k]);});window.addEventListener('keyup',e=>{this.keys.delete(e.code);this.blocked.delete(e.code);});window.addEventListener('blur',()=>this.clear());this.bindTouch();}
 clear(){for(const k of this.keys)this.blocked.add(k);this.keys.clear();this.holds.clear();this.pointer=null;this.touch.active=false;this.touch.x=0;this.touch.y=0;const k=document.querySelector('#joystick-knob');if(k)k.style.transform='';}
 setEnabled(value){this.clear();this.enabled=value;}
 read(yaw=0,cameraYaw=Math.atan2(39,56)){if(!this.enabled)return{throttle:0,steer:0,brake:false,boost:false};let throttle=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0);let steer=(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0)-(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0);if(this.touch.active){const target=Math.atan2(-this.touch.x,-this.touch.y)+cameraYaw;const d=Math.atan2(Math.sin(target-yaw),Math.cos(target-yaw));steer=Math.max(-1,Math.min(1,d*1.7));throttle=Math.min(1,Math.hypot(this.touch.x,this.touch.y));}if(this.holds.has('reverse'))throttle=-1;return{throttle,steer,brake:this.keys.has('Space')||this.holds.has('brake'),boost:this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')||this.holds.has('boost')};}
 bindTouch(){const pad=document.querySelector('#joystick'),knob=document.querySelector('#joystick-knob');this.pointer=null;const update=e=>{const b=pad.getBoundingClientRect();let x=(e.clientX-b.x-b.width/2)/(b.width/2),y=(e.clientY-b.y-b.height/2)/(b.height/2);const l=Math.max(1,Math.hypot(x,y));x/=l;y/=l;this.touch={active:true,x,y};knob.style.transform=`translate(${x*30}px,${y*30}px)`;};pad.addEventListener('pointerdown',e=>{if(!this.enabled)return;e.preventDefault();this.pointer=e.pointerId;pad.setPointerCapture(this.pointer);update(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===this.pointer&&this.enabled)update(e);});const end=()=>{this.pointer=null;this.touch={active:false,x:0,y:0};knob.style.transform='';};pad.addEventListener('pointerup',end);pad.addEventListener('pointercancel',end);pad.addEventListener('lostpointercapture',end);for(const b of document.querySelectorAll('[data-hold]')){b.addEventListener('pointerdown',e=>{if(!this.enabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);this.holds.add(b.dataset.hold);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>this.holds.delete(b.dataset.hold));}}
}
