import {CONTENT_IDS,groupFor,islandIdFor} from '../portfolio-groups.js';

// Public navigation bridge: content IDs stay valid as districts share four islands.
export function createVoyageTools({islands,read,travel,status:readStatus,close,play,interact,dock,steer,walk,board,practice,skipArrival}){
 const physicalIds=islands.map(i=>i.id),contentIds=CONTENT_IDS.filter(id=>physicalIds.includes(islandIdFor(id)));
 const choices=[...physicalIds,...contentIds];
 const status=()=>({...readStatus(),islands:islands.map(i=>({id:i.id,name:i.name,entryIds:groupFor(i.id)?.entryIds||[]})),contentMapping:Object.fromEntries(contentIds.map(id=>[id,islandIdFor(id)]))});
 const tools=[{name:'walk_jack',title:'Walk with Jack',description:'Move Jack on foot relative to the screen, then release input. Go ashore first.',inputSchema:{type:'object',properties:{right:{type:'number',minimum:-1,maximum:1},forward:{type:'number',minimum:-1,maximum:1},run:{type:'boolean'},durationMs:{type:'number',minimum:50,maximum:5000}},required:['right','forward','durationMs'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||![input.right,input.forward,input.durationMs].every(Number.isFinite)||Math.abs(input.right)>1||Math.abs(input.forward)>1||input.durationMs<50||input.durationMs>5000)throw new Error('Use direction from -1 to 1 and duration of 50–5000 ms.');await walk(input,input.durationMs);return status();}},{name:'steer_boat',title:'Drive the current vehicle',description:'Apply throttle and steering to the boat, garage car, quad bike, or campus bicycle currently being ridden, then release controls. Uses the same physics as keyboard and joystick. Panels and focus loss interrupt driving.',inputSchema:{type:'object',properties:{throttle:{type:'number',minimum:-1,maximum:1},steer:{type:'number',minimum:-1,maximum:1},boost:{type:'boolean'},brake:{type:'boolean'},durationMs:{type:'number',minimum:50,maximum:5000}},required:['throttle','steer','durationMs'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||!Number.isFinite(input.throttle)||Math.abs(input.throttle)>1||!Number.isFinite(input.steer)||Math.abs(input.steer)>1||!Number.isFinite(input.durationMs)||input.durationMs<50||input.durationMs>5000)throw new Error('Use throttle/steer from -1 to 1 and a duration of 50–5000 ms.');await steer({throttle:input.throttle,steer:input.steer,boost:!!input.boost,brake:!!input.brake},input.durationMs);return status();}},{name:'get_voyage_status',title:'Current voyage',description:'Read boat, challenge, local logbook and island navigation status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return status();}},
 {name:'navigate_portfolio_island',title:'Explore a portfolio island',description:'Read one of four island overviews or a specific portfolio story. Legacy story IDs remain valid; travel places Jack on foot on that story’s island bridge, parks the boat, and ends any active challenge. Every landing has a skippable island overview.',inputSchema:{type:'object',properties:{islandId:{type:'string',enum:choices},action:{type:'string',enum:['read','travel']}},required:['islandId','action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||!choices.includes(input.islandId)||!['read','travel'].includes(input.action))throw new Error('Choose a known island and read or travel.');if(input.action==='travel'){if(!status().available3D)throw new Error('Sea travel is unavailable; choose read.');await travel(islandIdFor(input.islandId));}else read(input.islandId);return status();}},
 {name:'play_archipelago',title:'Play in the archipelago',description:'Start one of three optional challenges, activate the nearest available device, go ashore or read the nearest exhibit, return to the boat, skip the arrival overview, or close the current panel. Starting a challenge ends the previous round.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start_buoy','start_cargo','start_lighthouse','interact','dock','board','close_panel','skip_arrival']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const a=input?.action;if(!['start_buoy','start_cargo','start_lighthouse','interact','dock','board','close_panel','skip_arrival'].includes(a))throw new Error('Choose a listed action.');if(a==='close_panel')close();else{if(!status().available3D)throw new Error('The sea is unavailable. Portfolio content remains readable.');if(a.startsWith('start_'))await play(a.slice(6));else if(a==='interact')interact();else if(a==='board')await board();else if(a==='skip_arrival')skipArrival?.();else await dock();}return status();}}];
 if(practice)tools.push({name:'garden_practice',title:'Practice tennis or putting',description:'Start practice while on foot on About island, move or aim sideways, hit a tennis ball, hold/release a putt, or leave. Uses the same controls and fixed physics as the page.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start_tennis','start_golf','move','aim','hit','putt','leave']},direction:{type:'number',minimum:-1,maximum:1},durationMs:{type:'number',minimum:50,maximum:1500}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||!['start_tennis','start_golf','move','aim','hit','putt','leave'].includes(input.action))throw Error('Choose a listed garden practice action.');if(input.direction!==undefined&&(!Number.isFinite(input.direction)||Math.abs(input.direction)>1))throw Error('Direction must be from -1 to 1.');if(input.durationMs!==undefined&&(!Number.isFinite(input.durationMs)||input.durationMs<50||input.durationMs>1500))throw Error('Duration must be 50–1500 ms.');await practice(input);return status();}});
 return tools;
}

export function registerVoyageTools(actions){
 const context=document.modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 for(const tool of createVoyageTools(actions))try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
}
