// Public navigation bridge: calls the same actions as the map and game UI.
export function registerVoyageTools({islands,read,travel,status,close,play,interact,dock,steer}){
 const context=document.modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const choices=islands.map(i=>i.id);
 const tools=[{name:'steer_boat',title:'Steer the boat',description:'Apply throttle and steering for a short voyage segment, then release controls. Uses the same boat physics as the keyboard and joystick. Panels and focus loss interrupt steering.',inputSchema:{type:'object',properties:{throttle:{type:'number',minimum:-1,maximum:1},steer:{type:'number',minimum:-1,maximum:1},boost:{type:'boolean'},brake:{type:'boolean'},durationMs:{type:'number',minimum:50,maximum:5000}},required:['throttle','steer','durationMs'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||!Number.isFinite(input.throttle)||Math.abs(input.throttle)>1||!Number.isFinite(input.steer)||Math.abs(input.steer)>1||!Number.isFinite(input.durationMs)||input.durationMs<50||input.durationMs>5000)throw new Error('Use throttle/steer from -1 to 1 and a duration of 50–5000 ms.');await steer({throttle:input.throttle,steer:input.steer,boost:!!input.boost,brake:!!input.brake},input.durationMs);return status();}},{name:'get_voyage_status',title:'Current voyage',description:'Read boat, challenge, local logbook and island navigation status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return status();}},
 {name:'navigate_portfolio_island',title:'Explore a portfolio island',description:'Read an island’s portfolio content or travel to its safe harbor. Travel ends any active local challenge.',inputSchema:{type:'object',properties:{islandId:{type:'string',enum:choices},action:{type:'string',enum:['read','travel']}},required:['islandId','action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||!choices.includes(input.islandId)||!['read','travel'].includes(input.action))throw new Error('Choose a known island and read or travel.');if(input.action==='travel'){if(!status().available3D)throw new Error('Sea travel is unavailable; choose read.');await travel(input.islandId);}else read(input.islandId);return status();}},
 {name:'play_archipelago',title:'Play in the archipelago',description:'Start one of three optional challenges, activate the nearest available device, dock and read, or close the current panel. Starting a challenge ends the previous round.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start_buoy','start_cargo','start_lighthouse','interact','dock','close_panel']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const a=input?.action;if(!['start_buoy','start_cargo','start_lighthouse','interact','dock','close_panel'].includes(a))throw new Error('Choose a listed action.');if(a==='close_panel')close();else{if(!status().available3D)throw new Error('The sea is unavailable. Portfolio content remains readable.');if(a.startsWith('start_'))await play(a.slice(6));else if(a==='interact')interact();else dock();}return status();}}];
 for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
}
