import * as THREE from 'three/webgpu';
import { color, mix, positionWorld, sin, uniform } from 'three/tsl';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
import RAPIER from '@dimforge/rapier3d-compat/rapier.es.js';
import { Events } from './core/Events.js';
import { BoatController } from './core/boat.js';
import { Race } from './core/race.js';
import { createIslandColliders,createBoundaryColliders } from './core/collisions.js';
import { islands,gates,boatSpawn,raceStart,WORLD_RADIUS,nearestIsland,inDockZone } from './config.js';
const vec=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.85,...extra});
export class Game{
 constructor(canvas,inputs,settings){this.canvas=canvas;this.inputs=inputs;this.settings=settings;this.events=new Events();this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#65bdbb');this.scene.fog=new THREE.Fog('#81c9c4',140,360);this.camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.3,600);this.mode='exploring';this.loaded=new Map();this.time=0;this.accumulator=0;this.wakes=[];this.colliders=[];this.race=new Race(gates,{best:settings.best||0,onFinish:(time,best)=>this.events.trigger('finish',[time,best])});this.loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);this.shoreMaterials=[];}
 async init(){
  this.renderer=new THREE.WebGPURenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance',forceWebGL:new URLSearchParams(location.search).has('webgl')});
  await this.renderer.init();this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.settings.quality==='low'?1:1.6));this.renderer.shadowMap.enabled=this.settings.quality!=='low';this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.06;
  await RAPIER.init();this.world=new RAPIER.World({x:0,y:0,z:0});this.world.timestep=1/60;this.boat=new BoatController(RAPIER,this.world,boatSpawn);this.prev=vec(boatSpawn.x,.35,boatSpawn.z);this.visualPosition=this.prev.clone();this.createLight();this.createWater();this.createIslands();this.createBoat();this.createBoundary();this.createGates();this.createToys();this.createWake();this.resetCamera();
  window.addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);});
  this.last=performance.now();this.renderer.setAnimationLoop(()=>{try{this.frame();}catch(error){this.renderer.setAnimationLoop(null);this.events.trigger('failure',[error]);}});this.events.trigger('ready',[this.renderer.backend.isWebGPUBackend?'WebGPU':'WebGL2']);
  this.loadModel('boat');this.loadModel('harbor');this.loadModel('connect');
 }
 mesh(geometry,material,parent=this.scene){const m=new THREE.Mesh(geometry,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 createLight(){this.scene.add(new THREE.HemisphereLight('#fff7d8','#397d80',2.0));this.sun=new THREE.DirectionalLight('#fff4d2',2.5);this.sun.position.set(-45,75,25);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:200});this.sun.shadow.normalBias=.15;this.sun.shadow.bias=-.0001;this.scene.add(this.sun,this.sun.target);}
 createWater(){this.waterTime=uniform(0);const water=new THREE.MeshStandardNodeMaterial({roughness:.36,metalness:.04});const p=positionWorld;const w=sin(p.x.mul(.28).add(p.z.mul(.33)).add(this.waterTime.mul(.55))).mul(sin(p.z.mul(.43).sub(this.waterTime.mul(.35)))).mul(.5).add(.5);water.colorNode=mix(color('#238e9f'),color('#46b6b5'),w.mul(.3).add(.25));this.water=this.mesh(new THREE.PlaneGeometry(1400,1400),water);this.water.rotation.x=-Math.PI/2;this.water.position.y=-.1;this.water.castShadow=false;
  const geo=new THREE.PlaneGeometry(1,.08);this.glints=new THREE.InstancedMesh(geo,new THREE.MeshBasicMaterial({color:'#bde9d7',transparent:true,opacity:.28,depthWrite:false}),350);const dummy=new THREE.Object3D();for(let i=0;i<350;i++){const x=Math.sin(i*127.1)*170,z=Math.cos(i*73.3)*170;dummy.position.set(x,.015,z);dummy.rotation.x=-Math.PI/2;dummy.rotation.z=Math.sin(i)*.3;dummy.scale.set(1+(i%5)*.3,1,1);dummy.updateMatrix();this.glints.setMatrixAt(i,dummy.matrix);}this.scene.add(this.glints);
 }
 createIslands(){for(const i of islands){const group=new THREE.Group();group.position.set(i.x,0,i.z);group.rotation.y=i.rotation;this.scene.add(group);this.loaded.set(i.id,{group,model:null,requested:false,island:i});
   // Coherent temporary diorama while the independent GLB is loading.
   this.mesh(new THREE.CylinderGeometry(9,11,1.5,32),mat('#eddca8'),group).position.y=.05;this.mesh(new THREE.CylinderGeometry(8.4,9,1,32),mat('#a7c97b'),group).position.y=.9;
   const lightHouse=this.mesh(new THREE.CylinderGeometry(1.0,1.4,8,16),mat('#fff7df'),group);lightHouse.position.y=5;const cap=this.mesh(new THREE.ConeGeometry(1.7,1.5,16),mat('#ef8054'),group);cap.position.y=9.6;const dock=this.mesh(new THREE.BoxGeometry(3,.45,7),mat('#b98050'),group);dock.position.set(0,.6,11.5);
   createIslandColliders(RAPIER,this.world,i);
   for(let j=0;j<3;j++){const material=new THREE.MeshBasicMaterial({color:j===0?'#91d3bf':j===1?'#b2dfc4':'#e1edc8',transparent:true,opacity:.16+j*.03,depthWrite:false});const shore=this.mesh(new THREE.CircleGeometry(13.8-j*.9,48),material);shore.rotation.x=-Math.PI/2;shore.position.set(i.x,.02+j*.005,i.z);shore.castShadow=false;shore.receiveShadow=false;this.shoreMaterials.push(material);}
  }}
 createBoat(){this.boatGroup=new THREE.Group();this.scene.add(this.boatGroup);this.boatVisual=new THREE.Group();this.boatGroup.add(this.boatVisual);const hull=this.mesh(new THREE.BoxGeometry(1.6,.6,3.6),mat('#f27c45'),this.boatVisual);hull.position.y=.35;const cabin=this.mesh(new THREE.BoxGeometry(1.25,.35,2.0),mat('#fff5df'),this.boatVisual);cabin.position.set(0,.8,-.2);this.boatGroup.position.copy(this.visualPosition);}
 async loadModel(id){const item=id==='boat'?null:this.loaded.get(id);if(item?.requested)return;if(item)item.requested=true;try{const gltf=await this.loader.loadAsync(`/models/${id}.glb`);gltf.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});if(id==='boat'){this.boatVisual.clear();this.boatVisual.add(gltf.scene);}else{item.group.clear();item.group.add(gltf.scene);item.model=gltf.scene;}this.events.trigger('asset',[id]);}catch(error){if(item)item.requested=false;console.warn('Model unavailable:',id,error.message);}}
 createBoundary(){const geo=new THREE.CylinderGeometry(.32,.5,.85,8),m=mat('#f6c36a');this.boundary=new THREE.InstancedMesh(geo,m,90);const dummy=new THREE.Object3D();for(let i=0;i<90;i++){const a=i/90*Math.PI*2;dummy.position.set(Math.cos(a)*WORLD_RADIUS,.3,Math.sin(a)*WORLD_RADIUS);dummy.updateMatrix();this.boundary.setMatrixAt(i,dummy.matrix);}createBoundaryColliders(RAPIER,this.world,WORLD_RADIUS);this.scene.add(this.boundary);}
 createGates(){this.gateGroups=[];for(let n=0;n<gates.length;n++){const g=gates[n],prev=n?gates[n-1]:raceStart;const angle=Math.atan2(g.nx,g.nz);g.angle=angle;const root=new THREE.Group();root.position.set(g.x,0,g.z);root.rotation.y=angle;for(const sign of [-1,1]){const buoy=this.mesh(new THREE.CylinderGeometry(.6,.85,1.1,12),mat('#f5b35b'),root);buoy.position.set(sign*g.r,.5,0);const pole=this.mesh(new THREE.CylinderGeometry(.1,.1,4,6),mat('#fff7e7'),root);pole.position.set(sign*g.r,2.5,0);const flag=this.mesh(new THREE.BoxGeometry(2,1.25,.08),mat('#f28a50'),root);flag.position.set(sign*g.r+.9,4,0);}const ring=this.mesh(new THREE.TorusGeometry(g.r,.1,4,48,Math.PI),new THREE.MeshBasicMaterial({color:'#ffe7a1',transparent:true,opacity:.25}),root);ring.position.y=.3;const label=this.makeNumber(n+1);label.position.set(0,6,0);root.add(label);root.visible=true;this.scene.add(root);this.gateGroups.push(root);}
  this.raceMarker=new THREE.Group();this.raceMarker.position.set(raceStart.x+6,.3,raceStart.z+5);this.mesh(new THREE.CylinderGeometry(1.2,1.6,.6,12),mat('#f2aa43'),this.raceMarker);const p=this.mesh(new THREE.CylinderGeometry(.14,.14,6,8),mat('#fff7df'),this.raceMarker);p.position.y=3;const f=this.mesh(new THREE.BoxGeometry(3,1.8,.1),mat('#244d59'),this.raceMarker);f.position.set(1.35,5,0);this.scene.add(this.raceMarker);
 }
 makeNumber(n){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const c=canvas.getContext('2d');c.fillStyle='#fff9e8';c.beginPath();c.arc(64,64,58,0,Math.PI*2);c.fill();c.fillStyle='#214f5d';c.font='bold 78px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(String(n),64,68);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));sprite.scale.set(4.5,4.5,1);return sprite;}
 createToys(){this.toys=[];const duck=new THREE.Group();const yellow=mat('#ffd25a');this.mesh(new THREE.SphereGeometry(.85,14,10),yellow,duck).scale.set(1,.75,1.2);this.mesh(new THREE.SphereGeometry(.55,12,10),yellow,duck).position.set(0,.75,-.55);const beak=this.mesh(new THREE.BoxGeometry(.55,.18,.45),mat('#ee8042'),duck);beak.position.set(0,.72,-1.04);for(const x of [-.3,.3])this.mesh(new THREE.SphereGeometry(.07,6,6),mat('#214953'),duck).position.set(x,.93,-.93);duck.position.set(-20,.65,64);this.scene.add(duck);const body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(-20,.65,64).setGravityScale(0).enabledTranslations(true,false,true).enabledRotations(false,true,false).setLinearDamping(1.4));this.world.createCollider(RAPIER.ColliderDesc.ball(.95).setDensity(.1).setRestitution(.5),body);this.toys.push({mesh:duck,body,id:'duck',lastHit:0});
  this.bottle=this.mesh(new THREE.CylinderGeometry(.26,.26,1.3,10),mat('#a8dec5',{transparent:true,opacity:.8}));this.bottle.position.set(25,.3,64);this.bottle.rotation.z=1.2;const cork=this.mesh(new THREE.CylinderGeometry(.16,.16,.2,8),mat('#b78054'),this.bottle);cork.position.y=.7;this.bottle.userData.easter='bottle';
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();let down=null;this.canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});this.canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8||this.mode!=='exploring')return;this.pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);if(this.raycaster.intersectObject(this.bottle,true).length)this.events.trigger('bottle');});
 }
 createWake(){this.wakeDummy=new THREE.Object3D();this.wakeMesh=new THREE.InstancedMesh(new THREE.CircleGeometry(1,10),new THREE.MeshBasicMaterial({color:'#d5f1df',transparent:true,opacity:.42,depthWrite:false}),100);this.wakeMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.scene.add(this.wakeMesh);this.wakeMesh.frustumCulled=false;this.lastWake=0;this.clearWake();}
 clearWake(){this.wakes=[];if(this.wakeMesh){this.wakeDummy.scale.setScalar(0);this.wakeDummy.updateMatrix();for(let i=0;i<100;i++)this.wakeMesh.setMatrixAt(i,this.wakeDummy.matrix);this.wakeMesh.instanceMatrix.needsUpdate=true;}}
 updateWake(dt){const pos=this.visualPosition,speed=this.boat.speed;const frozen=this.mode!=='exploring'||this.race.frozen;if(!frozen&&speed>.7&&this.time-this.lastWake>.055){this.lastWake=this.time;for(const sign of [-1,1])this.wakes.push({x:pos.x+Math.sin(this.boat.yaw)*1.8+Math.cos(this.boat.yaw)*sign*.4,z:pos.z+Math.cos(this.boat.yaw)*1.8-Math.sin(this.boat.yaw)*sign*.4,dx:Math.cos(this.boat.yaw)*sign,dz:-Math.sin(this.boat.yaw)*sign,t:this.time,scale:.25+speed*.012});}this.wakes=this.wakes.filter(w=>this.time-w.t<2).slice(-100);for(let i=0;i<100;i++){const w=this.wakes[i];if(w){const age=this.time-w.t;this.wakeDummy.position.set(w.x+w.dx*age*.8,.07,w.z+w.dz*age*.8);this.wakeDummy.rotation.set(-Math.PI/2,0,0);const scale=(w.scale+age*.35)*(1-age/2);this.wakeDummy.scale.set(scale*1.8,scale,1);}else this.wakeDummy.scale.setScalar(0);this.wakeDummy.updateMatrix();this.wakeMesh.setMatrixAt(i,this.wakeDummy.matrix);}this.wakeMesh.instanceMatrix.needsUpdate=true;}
 frame(){const now=performance.now(),dt=Math.min((now-this.last)/1000,.1);this.last=now;this.time+=dt;this.waterTime.value=this.settings.reduced?0:this.time;
  const paused=this.mode!=='exploring';const beforeRace=this.race.state;if(!paused){const p=this.boat.position;this.race.tick(p,p);}if(beforeRace!==this.race.state)this.events.trigger('racestate',[this.race.state]);const frozen=paused||this.race.frozen;
  if(!frozen){this.accumulator+=dt;while(this.accumulator>=1/60){const p={...this.boat.position};this.prev.set(p.x,p.y,p.z);this.boat.step(this.inputs.read(this.boat.yaw,Math.atan2(innerWidth<700?34:39,innerWidth<700?61:56)),1/60);const distance=Math.hypot(p.x,p.z);if(distance>WORLD_RADIUS-10){const v=this.boat.velocity,outward=(v.x*p.x+v.z*p.z)/distance;if(outward>0){const strength=Math.min(1,(distance-WORLD_RADIUS+10)/10);this.boat.body.setLinvel({x:v.x-p.x/distance*outward*strength*.1,y:0,z:v.z-p.z/distance*outward*strength*.1},true);}}this.world.step();this.race.tick(p,this.boat.position);this.accumulator-=1/60;if(this.mode!=='exploring'||this.race.frozen)break;}}else this.accumulator=0;
  const p=this.boat.position;this.visualPosition.lerpVectors(this.prev,vec(p.x,p.y,p.z),frozen?1:Math.min(this.accumulator*60,1));this.boatGroup.position.copy(this.visualPosition);this.boatGroup.rotation.y=this.boat.yaw;const input=this.inputs.read(this.boat.yaw,Math.atan2(innerWidth<700?34:39,innerWidth<700?61:56));this.boatVisual.position.y=this.settings.reduced?0:Math.sin(this.time*2.2)*.06;this.boatVisual.rotation.z=THREE.MathUtils.damp(this.boatVisual.rotation.z,this.settings.reduced?0:-input.steer*this.boat.speed*.004,5,dt);this.boatVisual.rotation.x=THREE.MathUtils.damp(this.boatVisual.rotation.x,this.settings.reduced?0:-Math.max(0,this.boat.forwardSpeed)*.0025,4,dt);
  for(const toy of this.toys){const tp=toy.body.translation();toy.mesh.position.set(tp.x,tp.y+(this.settings.reduced?0:Math.sin(this.time*2)*.07),tp.z);toy.mesh.quaternion.copy(toy.body.rotation());if(Math.hypot(tp.x-p.x,tp.z-p.z)<2.8&&this.boat.speed>1&&now-toy.lastHit>3000){toy.lastHit=now;this.events.trigger('duck');}}this.bottle.position.y=.25+(this.settings.reduced?0:Math.sin(this.time)*.09);
  this.updateLandmarks(dt);this.updateWake(dt);this.updateCamera(dt);this.updateNearby(now);this.sun.position.set(p.x-45,75,p.z+25);this.sun.target.position.set(p.x,0,p.z);this.sun.target.updateMatrixWorld();this.events.trigger('frame',[{position:p,yaw:this.boat.yaw,speed:this.boat.speed,dt,now,frozen}]);this.renderer.render(this.scene,this.camera);
  if(Math.hypot(p.x,p.z)>WORLD_RADIUS+9)this.events.trigger('rescue');
 }
 updateNearby(now){let nearest=null,distance=Infinity;for(const i of islands){const d=Math.hypot(this.boat.position.x-i.dock.x,this.boat.position.z-i.dock.z);if(inDockZone(this.boat.position,i)&&d<distance){nearest=i;distance=d;}const asset=this.loaded.get(i.id);if(!asset.model&&!asset.requested&&d<105&&(!asset.lastAttempt||now-asset.lastAttempt>12000)){asset.lastAttempt=now;this.loadModel(i.id);}}this.nearby=nearest;this.nearRace=Math.hypot(this.boat.position.x-raceStart.x,this.boat.position.z-raceStart.z)<10;for(let n=0;n<this.gateGroups.length;n++){this.gateGroups[n].visible=true;this.gateGroups[n].traverse(o=>{if(o.isMesh&&o.material.transparent)o.material.opacity=n===this.race.index ? .55 : .1;});}}
 updateCamera(dt){const p=this.visualPosition;let target,position;if(this.focus){const i=this.focus;target=vec(i.x+(innerWidth>700?12:0),3,i.z-(innerWidth>700?9:0));position=target.clone().add(vec(28,29,39));}else{const zoom=this.settings.reduced?0:this.boat.speed*.32;const portrait=innerWidth<700;const camYaw=Math.atan2(34,61);target=p.clone().add(portrait?vec(-Math.sin(camYaw)*8-Math.sin(this.boat.yaw)*3,0,-Math.cos(camYaw)*8-Math.cos(this.boat.yaw)*3):vec(-Math.sin(this.boat.yaw)*12-8,0,-Math.cos(this.boat.yaw)*12));position=target.clone().add(vec(portrait?34:39,portrait?53+zoom:47+zoom,portrait?61+zoom:56+zoom));}const rate=this.settings.reduced?1:1-Math.exp(-3*dt);this.camera.position.lerp(position,rate);this.cameraTarget.lerp(target,rate);this.camera.lookAt(this.cameraTarget);}
 resetCamera(){const p=this.boat.position;this.visualPosition.set(p.x,p.y,p.z);this.prev.copy(this.visualPosition);this.cameraTarget=vec(p.x-12,0,p.z-12);this.camera.position.copy(this.cameraTarget).add(vec(39,47,56));this.camera.lookAt(this.cameraTarget);}
 pause(kind='read',focus=null){if(focus&&this.loaded?.has(focus.id))this.loadModel(focus.id);if(this.mode==='exploring'){this.snapshot=this.boat.snapshot();this.race.pause();}this.mode=kind;this.focus=focus;this.inputs.setEnabled(false);}
 dock(i){this.race.cancel();this.snapshot=null;this.boat.hold();this.pause('dock',i);this.snapshot=null;}
 resume(){if(this.snapshot&&this.race.active)this.boat.restore(this.snapshot);else this.boat.hold();this.snapshot=null;this.focus=null;this.mode='exploring';this.race.resume();this.inputs.setEnabled(true);this.last=performance.now();}
 teleport(point){this.race.cancel();this.snapshot=null;this.focus=null;this.mode='exploring';this.boat.teleport(point);this.accumulator=0;this.clearWake();this.resetCamera();this.inputs.setEnabled(true);}
 reset(){const i=nearestIsland(this.boat.position);this.teleport({...i.dock,yaw:i.yaw});return i;}
 startRace(){this.teleport(raceStart);this.race.start();}
 setQuality(level){this.settings.quality=level;this.renderer.setPixelRatio(Math.min(devicePixelRatio,level==='low'?1:1.6));this.renderer.shadowMap.enabled=level!=='low';this.glints.visible=level!=='low';}
 updateLandmarks(dt){for(const item of this.loaded.values()){if(!item.model)continue;const active=this.focus?.id===item.island.id;item.model.traverse(o=>{if(!o.isMesh)return;const name=o.material.name;const glowing=active&&['glass','glassBlue','yellow','orange'].includes(name);o.material.emissive.set(glowing?'#ffca77':'#000000');o.material.emissiveIntensity=glowing ? .15+(this.settings.reduced?0:Math.sin(this.time*2)*.05) : 0;});} }
 project(point){return vec(point.x,point.y||0,point.z).project(this.camera);}
}
