import './style.css';
import {registerVoyageTools} from './core/webmcp.js';
import content from './content.json';
import {islands,gates,nearestIsland,WORLD_RADIUS} from './config.js';
import {Inputs} from './core/inputs.js';
import {formatTime} from './core/race.js';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage={get(){try{return JSON.parse(localStorage.getItem('jack-archipelago-v1')||'{}')}catch{return{}}},set(data){try{localStorage.setItem('jack-archipelago-v1',JSON.stringify(data))}catch{}}};
const settings={sound:false,quality:matchMedia('(pointer:coarse)').matches?'low':'high',reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,best:0,...storage.get()};settings.best=Number.isFinite(settings.best)&&settings.best>0?settings.best:0;settings.quality=settings.quality==='low'?'low':'high';
document.body.classList.toggle('reduced',settings.reduced);const inputs=new Inputs();let game=null,fallbackGame=null,visited=new Set(),returnFocus=null,currentId=null,toastTimer,activeCategory='all',currentMapId='harbor',travelToken=0,visibilityPaused=false;
let audio=null;function sound(kind='click'){if(!settings.sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='duck'?'triangle':'sine';o.frequency.setValueAtTime(kind==='duck'?540:kind==='finish'?660:380,audio.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='duck'?220:880,audio.currentTime+.16);g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.23);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.24);}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function save(){storage.set(settings);}
function showPanel(markup,{id=null,focus=null,dock=false}={}){if(!$('#panel').open)returnFocus=document.activeElement;currentId=id;$('#panel-content').innerHTML=markup;if(!$('#panel').open)$('#panel').showModal();$('#panel').scrollTop=0;$('#panel-close').focus();if(game?.boat){if(dock)game.dock(focus);else game.pause('read',focus);}inputs.setEnabled(false);sound();}
function closePanel({resume=true}={}){if(!$('#panel').open)return;$('#panel').close();currentId=null;if(resume&&game?.boat)game.resume();inputs.setEnabled(resume);returnFocus?.focus?.();}
function card(entry){return `<button class="directory-card" data-open="${entry.id}"><span class="arrow">↗</span><small>${esc(entry.category==='experience'?'WORK EXPERIENCE':entry.category==='project'?'PROJECT':entry.eyebrow)}</small><h3>${esc(entry.title)}</h3><p>${esc(entry.summary)}</p></button>`;}
function markVisited(id){visited.add(id);$('#visited-label').textContent=`${visited.size} of 9 islands explored`;$('#journey-dots').innerHTML=islands.map(i=>`<i class="${visited.has(i.id)?'seen':''}"></i>`).join('');}
function openEntry(id,{dock=false}={}){const e=content.find(x=>x.id===id);if(!e)return;markVisited(id);const i=islands.find(x=>x.id===id);const links=e.links.filter(l=>/^https:\/\/|^mailto:|^\/resume\.pdf$/.test(l.url));const sections=`${e.contributions.length?`<section class="panel-section"><h3>${id==='learning'?'Education':id==='connect'?'Let’s talk about':id==='harbor'?'What I build':'My contribution'}</h3><ul>${e.contributions.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`:''}${e.results.length?`<section class="panel-section"><h3>${id==='learning'?'Academic record':'Highlights'}</h3><ul>${e.results.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`:''}${e.technologies.length?`<section class="panel-section"><h3>Tools of the trade</h3><div class="tags">${e.technologies.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></section>`:''}`;
 showPanel(`<span class="eyebrow">ISLAND ${String(i.n).padStart(2,'0')} / ${esc(e.eyebrow)}</span><h2 class="panel-hero" id="panel-title">${esc(e.title)}</h2>${e.period?`<p class="panel-period">${esc(e.period)}</p>`:''}<p class="panel-summary">${esc(e.summary)}</p>${sections}<div class="panel-links">${links.map(l=>`<a class="primary-button" href="${esc(l.url)}" ${l.url.startsWith('mailto:')?'':'target="_blank" rel="noopener noreferrer"'}>${esc(l.label)} ↗</a>`).join('')}${game?`<button class="secondary-button" data-travel="${id}">Sail from this island ↗</button>`:''}</div><p class="panel-footnote">${['experience','project'].includes(e.category)?'Project details and results are drawn from my résumé. The island is a playful illustration of the work.':'A little island in a bigger story.'}</p>`,{id,focus:game?i:null,dock});}
function openDirectory(category='all'){activeCategory=category;const filtered=content.filter(e=>category==='all'||e.category===category||(category==='about'&&e.id==='harbor'));showPanel(`<span class="eyebrow">THE SCENIC SHORTCUT</span><h2 class="panel-hero" id="panel-title">${category==='project'?'Things I’ve built.':category==='experience'?'Where I’ve worked.':category==='about'?'A little about me.':'Choose your next island.'}</h2><p class="panel-summary">A collection of systems, products, and ideas. Pick an island to look around.</p><div class="directory-groups">${[['all','All islands'],['project','Projects'],['experience','Experience'],['about','About']].map(([k,v])=>`<button data-category="${k}" class="${k===category?'active':''}">${v}</button>`).join('')}</div>${filtered.map(card).join('')}`);}
function mapMarkup(id){const e=content.find(e=>e.id===id);return `<span class="eyebrow">CHART YOUR COURSE</span><h2 class="panel-hero" id="panel-title">Nine islands.<br>One curious mind.</h2><p class="panel-summary">Choose a destination. Take a closer look, or meet me at the dock.</p><div class="map-large" aria-label="Island destinations">${islands.map(i=>`<button data-map-id="${i.id}" class="${i.id===id?'active':''}" style="left:${50+i.x/2.6}%;top:${50+i.z/2.9}%" aria-label="${esc(i.name)}">${i.n}</button>`).join('')}</div><span class="eyebrow">${esc(islands.find(i=>i.id===id).name)}</span><h3>${esc(e.title)}</h3><p class="panel-summary">${esc(e.summary)}</p><div class="panel-links"><button class="primary-button" data-open="${id}">Read now ↗</button>${game?`<button class="secondary-button" data-travel="${id}">Travel here ⤴</button>`:''}</div>`;}
function openMap(id=currentMapId){currentMapId=id;showPanel(mapMarkup(id));}
async function travel(id){const i=islands.find(i=>i.id===id);if(!i||!game)return;const token=++travelToken;closePanel({resume:false});game.race.cancel();game.snapshot=null;game.inputs.setEnabled(false);$('#travel-fade').classList.add('active');await new Promise(r=>setTimeout(r,180));if(token!==travelToken)return;game.teleport({...i.dock,yaw:i.yaw});$('.intro').classList.add('compact');$('#travel-fade').classList.remove('active');toast(`Welcome to ${i.name}. Press E to explore.`);}
function openSettings(){showPanel(`<span class="eyebrow">MAKE YOURSELF AT HOME</span><h2 class="panel-hero" id="panel-title">Smooth sailing.</h2><label class="setting-row"><span>Sound<small>Little splashes and playful feedback</small></span><input id="setting-sound" type="checkbox" ${settings.sound?'checked':''}></label><label class="setting-row"><span>Visual quality<small>Low uses fewer effects and less power</small></span><select id="setting-quality"><option value="high" ${settings.quality==='high'?'selected':''}>High</option><option value="low" ${settings.quality==='low'?'selected':''}>Low</option></select></label><label class="setting-row"><span>Reduce motion<small>Steadier boat and camera</small></span><input id="setting-motion" type="checkbox" ${settings.reduced?'checked':''}></label><section class="panel-section"><h3>At the helm</h3><p class="panel-summary">W / ↑: throttle<br>S / ↓: brake and reverse<br>A D / ← →: steer<br>Shift: boost · Space: brake<br>E: dock · M: map · R: reset</p></section><button class="secondary-button" id="reading-mode">Browse without 3D ↗</button><p class="panel-footnote">Built with Three.js and Rapier. Architecture inspired by Bruno Simon’s folio-2025, with original boat and island models.</p>`);}
function openRace(){showPanel(`<span class="eyebrow">A LITTLE DETOUR</span><h2 class="panel-hero" id="panel-title">Buoy Run.</h2><p class="panel-summary">Six gates. Open water. Just you and the clock.</p><section class="panel-section"><h3>Your course</h3><ul><li>Pass through all six numbered gates in order.</li><li>Hold Shift to boost; use Space for tighter turns.</li><li>Docking, resetting, or traveling ends your run.</li><li>Your best time stays in this browser.</li></ul></section>${settings.best?`<p class="eyebrow">PERSONAL BEST</p><div class="race-result">${formatTime(settings.best)}</div>`:''}<div class="panel-links"><button class="primary-button" id="start-race" ${!game?'disabled':''}>Start run ↗</button></div>`);}
function raceFinished(time,best){settings.best=best;save();sound('finish');showPanel(`<span class="eyebrow">SIX GATES, BEAUTIFULLY SAILED</span><h2 class="panel-hero" id="panel-title">Nice run, captain.</h2><div class="race-result">${formatTime(time)}</div><p class="panel-summary">Personal best: <strong>${formatTime(best)}</strong></p><div class="panel-links"><button id="start-race" class="primary-button">Race again ↗</button><button id="return-exploring" class="secondary-button">Back to exploring</button></div>`);}
function toggleSound(value=!settings.sound){settings.sound=value;save();$('#sound-button').setAttribute('aria-pressed',String(value));$('#sound-button').setAttribute('aria-label',value?'Disable sound':'Enable sound');$('#sound-button').title=value?'Sound on':'Sound off';$('#sound-button').innerHTML=value?'♫':'♫<span class="slash"></span>';if(value)sound();}
$('#panel-close').onclick=()=>closePanel();$('#panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});$('#panel').addEventListener('click',e=>{if(e.target===$('#panel')){const b=$('#panel').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closePanel();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-open],[data-category],[data-travel],[data-map-id]');if(b){if(b.dataset.open)openEntry(b.dataset.open);else if(b.dataset.category)openDirectory(b.dataset.category);else if(b.dataset.travel)travel(b.dataset.travel);else if(b.dataset.mapId){currentMapId=b.dataset.mapId;$('#panel-content').innerHTML=mapMarkup(currentMapId);}}if(e.target.closest('#start-race')&&game){closePanel({resume:false});game.startRace();inputs.setEnabled(true);$('.intro').classList.add('compact');}if(e.target.closest('#return-exploring'))closePanel();if(e.target.closest('#reading-mode')){closePanel();enableFallback(false);}});
document.addEventListener('change',e=>{if(e.target.id==='setting-sound')toggleSound(e.target.checked);if(e.target.id==='setting-quality'){settings.quality=e.target.value;game?.setQuality(settings.quality);save();}if(e.target.id==='setting-motion'){settings.reduced=e.target.checked;document.body.classList.toggle('reduced',settings.reduced);save();}});
$('#back-to-sea').onclick=()=>{if(fallbackGame){game=fallbackGame;fallbackGame=null;document.body.classList.remove('no-3d');$('#fallback').hidden=true;game.resume();game.renderer.setAnimationLoop(()=>game.frame());}else location.href=location.pathname;};$('#touch-reset').onclick=()=>$('#reset-button').click();
$('#browse-button').onclick=()=>openDirectory();$('#mobile-menu').onclick=()=>openDirectory();$('#minimap-button').onclick=()=>openMap();$('#settings-button').onclick=openSettings;$('#sound-button').onclick=()=>toggleSound();$('#race-button').onclick=openRace;$('#race-exit').onclick=()=>{game?.race.cancel();toast('Run ended. There’s more to explore.');};$('#reset-button').onclick=()=>{if(game){const i=game.reset();toast(`Back in safe water near ${i.name}.`);}};
$('#dock-button').onclick=()=>dock();function dock(){if(!game||$('#panel').open)return;if(game.nearby)openEntry(game.nearby.id,{dock:true});else if(game.nearRace)openRace();}
inputs.events.on('action',key=>{if(key==='KeyM')openMap();if(key==='KeyE'||key==='Enter')dock();if(key==='KeyR'&&game){game.reset();toast('A fresh start in safe water.');}});
document.addEventListener('visibilitychange',()=>{if(!game)return;if(document.hidden){visibilityPaused=true;game.pause('hidden',game.focus);inputs.clear();audio?.suspend();}else{game.last=performance.now();if(visibilityPaused&&!$('#panel').open&&!document.body.classList.contains('no-3d'))game.resume();visibilityPaused=false;}});
window.addEventListener('blur',()=>{if(game&&!$('#panel').open){visibilityPaused=true;game.pause('hidden');}});window.addEventListener('focus',()=>{if(game&&visibilityPaused&&!document.hidden&&!$('#panel').open){visibilityPaused=false;game.resume();}});
const mini=$('#minimap'),ctx=mini.getContext('2d');function drawMap(p={x:0,z:67},yaw=0){const w=mini.width,h=mini.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#e1eee1';ctx.beginPath();ctx.ellipse(w/2,h/2,w*.45,h*.43,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ceddd2';ctx.setLineDash([3,5]);ctx.beginPath();ctx.ellipse(w/2,h/2,w*.36,h*.38,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(const i of islands){const x=w/2+i.x*.87,z=h/2+i.z*.75;ctx.fillStyle=visited.has(i.id)?'#c9905b':'#879d80';ctx.beginPath();ctx.ellipse(x,z,10,6,-.25,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fffaf0';ctx.font='bold 9px sans-serif';ctx.textAlign='center';ctx.fillText(String(i.n),x,z+3);}if(game?.race.active){ctx.strokeStyle='#dd9651';ctx.setLineDash([4,4]);ctx.beginPath();gates.forEach((g,n)=>{const x=w/2+g.x*.87,z=h/2+g.z*.75;n?ctx.lineTo(x,z):ctx.moveTo(x,z);});ctx.stroke();ctx.setLineDash([]);gates.forEach((g,n)=>{ctx.fillStyle=n===game.race.index?'#e77840':'#a7b99c';ctx.beginPath();ctx.arc(w/2+g.x*.87,h/2+g.z*.75,n===game.race.index?6:3,0,Math.PI*2);ctx.fill();});}const x=w/2+p.x*.87,z=h/2+p.z*.75;ctx.save();ctx.translate(x,z);ctx.rotate(-yaw);ctx.fillStyle='#e67643';ctx.strokeStyle='#fffdf5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(6,6);ctx.lineTo(0,3);ctx.lineTo(-6,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
let lastUI=0,engine=null,boundaryWarned=false;function frame({position,yaw,speed,dt,now,frozen}){if(speed>1)$('.intro').classList.add('compact');if(now-lastUI<45)return;lastUI=now;drawMap(position,yaw);const atBoundary=Math.hypot(position.x,position.z)>WORLD_RADIUS-12;if(atBoundary&&!boundaryWarned)toast('Open water ahead. Turn back toward the islands.');boundaryWarned=atBoundary;for(const i of islands){const node=document.querySelector(`[data-label="${i.id}"]`),p=game.project({x:i.x,y:13,z:i.z});const distance=Math.hypot(position.x-i.x,position.z-i.z);const visible=p.z<1&&p.x>-1.1&&p.x<1.1&&p.y>-.6&&p.y<.65&&distance<110&&!$('#panel').open;node.style.opacity=visible?'1':'0';node.style.left=`${(p.x*.5+.5)*innerWidth}px`;node.style.top=`${(-p.y*.5+.5)*innerHeight}px`;}
 const near=game.nearby;const show=!$('#panel').open&&!document.body.classList.contains('no-3d')&&(near||(game.nearRace&&!game.race.active));$('#dock-prompt').hidden=!show;if(show){$('#dock-name').textContent=near?near.name:'BUOY RUN';$('#dock-button').innerHTML=`<kbd>E</kbd> ${near?(game.race.active?'Dock · end run':'Dock & explore'):'Start a buoy run'} <span>↗</span>`;}
 const race=game.race;$('#race-hud').hidden=!race.active;$('#race-time').textContent=formatTime(race.elapsed);$('#race-progress').textContent=`${race.index} / 6 gates`;const gate=gates[race.index];if(race.active&&gate){const delta=Math.atan2(gate.x-position.x,-(gate.z-position.z))+Math.atan2(39,56);$('#race-bearing').innerHTML=`<b style="display:inline-block;transform:rotate(${delta}rad)">↑</b> Gate ${race.index+1} · ${Math.round(Math.hypot(gate.x-position.x,gate.z-position.z))} m`;}
 const count=['countdown','resuming'].includes(race.state)&&!$('#panel').open;$('#countdown').hidden=!count;if(count)$('#countdown').textContent=Math.max(1,Math.ceil((race.deadline-performance.now())/1000));
 const canInput=game.mode==='exploring'&&!race.frozen;if(inputs.enabled!==canInput)inputs.setEnabled(canInput);
 if(settings.sound&&audio){try{if(audio.state==='suspended'&&!frozen)audio.resume();if(!engine){const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.connect(gain).connect(audio.destination);gain.gain.value=0;osc.start();engine={osc,gain};}engine.osc.frequency.setTargetAtTime(48+speed*4,audio.currentTime,.15);engine.gain.gain.setTargetAtTime(frozen?0:Math.min(speed*.0014,.025),audio.currentTime,.2);}catch{}}else if(engine)engine.gain.gain.setTargetAtTime(0,audio.currentTime,.1);
}
function enableFallback(failed=true){document.body.classList.add('no-3d');$('#loading').hidden=true;$('#fallback').hidden=false;$('#fallback-cards').innerHTML=content.map(card).join('');$('.intro').classList.remove('compact');if(game){if(game.boat){game.pause('reading');fallbackGame=failed?null:game;}game.renderer?.setAnimationLoop(null);game=null;}$('#back-to-sea').textContent=fallbackGame?'Back to the sea ↗':'Try the sea again ↗';if(failed)toast('The sea is taking a break. Every island is still here to explore.');}
markVisited('harbor');drawMap();toggleSound(settings.sound);$('#island-labels').innerHTML=islands.map(i=>`<div class="island-label" data-label="${i.id}" style="opacity:0"><span class="number">${String(i.n).padStart(2,'0')}</span>${esc(i.name)}</div>`).join('');
async function boot(){if(new URLSearchParams(location.search).has('no3d')){enableFallback(false);return;}try{const {Game}=await import('./game.js');game=new Game($('#world'),inputs,settings);game.events.on('failure',error=>{console.error('Sea rendering stopped:',error);enableFallback();});game.events.on('ready',renderer=>{$('#loading').hidden=true;document.body.dataset.renderer=renderer;});game.events.on('frame',frame);game.events.on('finish',raceFinished);game.events.on('duck',()=>{sound('duck');toast('Quack! You’ve met the harbor master.');});game.events.on('bottle',()=>{sound();toast('A message from the sea: Hello, world.');});game.events.on('rescue',()=>{game.reset();toast('A little rescue. Welcome back to the archipelago.');});await game.init();if($('#panel').open)game.pause('read');if(import.meta.env.DEV){window.__archipelago={game,openEntry,openMap,travel,settings,inputs,closePanel};}$('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();enableFallback();});}catch(error){console.error('3D initialization:',error);enableFallback();}}
boot();
registerVoyageTools({islands,read:openEntry,travel,status:()=>({available3D:!!game?.boat,mode:game?.mode||'reading',position:game?.boat?{...game.boat.position}:null,speed:game?.boat?.speed||0,race:game?.race?{state:game.race.state,index:game.race.index,elapsed:game.race.elapsed}:null,panel:currentId,islands:islands.map(i=>({id:i.id,name:i.name}))})});
