import './style.css';
import content from './content.json';
import {islands,gates,challenges,lamps,WORLD_RADIUS,toWorld} from './config.js';
import {Inputs} from './core/inputs.js';
import {formatTime} from './core/race.js';
import {DiscoveryStore,SECRETS} from './core/discovery.js';
import {ZOOM_NAMES} from './core/camera.js';
import {LIVERIES} from './world/boat-appearance.js';
import {SEA_LIFE} from './world/marine.js';
import {registerVoyageTools} from './core/webmcp.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store=new DiscoveryStore({defaults:{quality:matchMedia('(pointer:coarse)').matches?'low':'high',reduced:matchMedia('(prefers-reduced-motion:reduce)').matches},onChange:({kind,id}={})=>{$('#stamp-count').textContent=`${store.stamps} / 18`;if(kind==='seaLife')toast(`First sighting · ${SEA_LIFE.find(s=>s.id===id)?.name}`);}}),settings=store.settings,inputs=new Inputs();
let game=null,fallbackGame=null,currentId=null,returnFocus=null,toastTimer,travelToken=0,visibilityPaused=false,audio=null,engine=null;
function sound(kind='click',strength=1){if(!settings.sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=kind==='wood'||kind.startsWith('horn')?'triangle':'sine';o.frequency.setValueAtTime(({duck:540,wood:140,water:230,bell:900,finish:660,gate:720,horn:175,'horn-reply':145,gull:1400,engine:55})[kind]||420,t);o.frequency.exponentialRampToValueAtTime(kind==='engine'?58:kind.startsWith('horn')?155:kind==='gull'?1900:kind==='duck'?220:kind==='wood'?65:880,t+(kind.startsWith('horn')?.6:.17));const duration=kind==='engine'?1.2:kind.startsWith('horn')?.7:.25;g.gain.setValueAtTime(.035*Math.min(1.5,strength),t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(audio.destination);o.start();o.stop(t+duration+.01);}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function showPanel(markup,{id=null,focus=null,dock=false}={}){if(!$('#panel').open)returnFocus=document.activeElement;currentId=id;document.body.classList.toggle('boat-studio',id==='studio');$('.intro').classList.add('compact');$('#panel-content').innerHTML=markup;if(!$('#panel').open)$('#panel').showModal();$('#panel').scrollTop=0;$('#panel-close').focus();if(game?.boat){if(dock)game.dock(focus);else game.pause('read',focus);}inputs.setEnabled(false);sound();}
function closePanel({resume=true}={}){if(!$('#panel').open)return;$('#panel').close();document.body.classList.remove('boat-studio');currentId=null;if(resume&&game?.boat&&!document.hidden)game.resume();if(returnFocus?.isConnected)returnFocus.focus();else $('#world').focus();}
function card(e){return `<button class="directory-card" data-open="${e.id}"><span class="arrow">↗</span><small>${esc(e.eyebrow)}</small><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p></button>`;}
function openEntry(id,{dock=false}={}){const e=content.find(x=>x.id===id),i=islands.find(x=>x.id===id);if(!e)return;store.see(id);const links=e.links.filter(l=>/^https:\/\/|^mailto:|^\/resume\.pdf$/.test(l.url));showPanel(`<span class="eyebrow">ISLAND ${String(i.n).padStart(2,'0')} / ${esc(e.eyebrow)}</span><h2 class="panel-hero" id="panel-title">${esc(e.title)}</h2>${e.period?`<p class="panel-period">${esc(e.period)}</p>`:''}<p class="panel-summary">${esc(e.summary)}</p>${[[id==='learning'?'Education':'My contribution',e.contributions],['Highlights',e.results]].filter(([,items])=>items.length).map(([title,items])=>`<section class="panel-section"><h3>${title}</h3><ul>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`).join('')}${e.technologies.length?`<section class="panel-section"><h3>Tools of the trade</h3><div class="tags">${e.technologies.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></section>`:''}<div class="panel-links">${links.map(l=>`<a class="primary-button" href="${esc(l.url)}" ${l.url.startsWith('mailto:')?'':'target="_blank" rel="noopener noreferrer"'}>${esc(l.label)} ↗</a>`).join('')}${game?`<button class="secondary-button" data-travel="${id}">Travel here ⤴</button>`:''}</div>${id==='harbor'&&game?'<button class="studio-entry" data-studio>Boat Studio <span>Choose your colours ↗</span></button>':''}<p class="panel-footnote">${['experience','project'].includes(e.category)?'Concept illustration · The island’s playful devices illustrate a theme. Résumé details above describe the actual work.':'A little island in a bigger story.'}</p>`,{id,focus:game?i:null,dock});}
function openDirectory(category='all'){showPanel(`<span class="eyebrow">THE SCENIC SHORTCUT</span><h2 class="panel-hero" id="panel-title">${category==='project'?'Things I’ve built.':category==='experience'?'Where I’ve worked.':category==='about'?'A little about me.':'Choose your next island.'}</h2><p class="panel-summary">Every story is one click away.</p><div class="directory-groups">${[['all','All islands'],['project','Projects'],['experience','Experience'],['about','About']].map(([k,v])=>`<button data-category="${k}" class="${k===category?'active':''}">${v}</button>`).join('')}</div>${content.filter(e=>category==='all'||e.category===category||(category==='about'&&['harbor','learning'].includes(e.id))).map(card).join('')}`,{id:'directory'});}
function openMap(id='harbor'){const island=islands.find(i=>i.id===id),challenge=challenges.find(c=>c.id===id),item=island||challenge;showPanel(`<span class="eyebrow">CHART YOUR COURSE</span><h2 class="panel-hero" id="panel-title">Your little world.</h2><p class="panel-summary">Nine stories. Three detours. A few things to discover along the way.</p><div class="map-large" aria-label="Island and challenge destinations"><svg viewBox="0 0 320 320" aria-hidden="true">${islands.map(i=>`<polygon fill="#afc5a5" stroke="#eee6bf" stroke-width="2" points="${i.shore.map(([x,z])=>{const p=toWorld(i,x,z);return `${160+p.x},${160+p.z}`;}).join(' ')}"/>`).join('')}</svg>${[...islands,...challenges].map(i=>`<button data-map-id="${i.id}" class="${i.id===id?'active':''} ${i.n?'':'game-pin'}" style="left:${50+i.x/3.2}%;top:${50+i.z/3.2}%" aria-label="${esc(i.name)}">${i.n||'⚑'}<span class="map-pin-name">${esc(i.name)}</span></button>`).join('')}</div><span class="eyebrow">${island?'PORTFOLIO ISLAND':'OPTIONAL CHALLENGE'}</span><h3>${esc(item.name)}</h3><p class="panel-summary">${esc(island?content.find(e=>e.id===id).summary:challenge.eyebrow)}</p><div class="panel-links">${island?`<button class="primary-button" data-open="${id}">Read now ↗</button>${game?`<button class="secondary-button" data-travel="${id}">Travel here ⤴</button>`:''}`:`<button class="primary-button" data-challenge="${id}">How to play ↗</button>`}</div><button class="text-link" data-logbook>Open your logbook →</button>`,{id:'map'});}
function bearing(target,position){const d=Math.atan2(target.x-position.x,-(target.z-position.z))+game.cameraRig.yaw;return `<b style="display:inline-block;transform:rotate(${d}rad)">↑</b> ${esc(target.name||'Next light')} · ${Math.round(Math.hypot(target.x-position.x,target.z-position.z))} m`;}
const gameCopy={buoy:{tag:'SIX GATES · OPEN WATER',title:'Buoy Run.',intro:'A wide-open lap around the archipelago.',steps:['Pass through six numbered gates in order. Follow the arrow to the next gate.','Use Shift to boost on straight stretches. Space slows you for a turn.','Missed a gate? Circle back and cross in the direction of the course.'],start:'Start run'},cargo:{tag:'THREE BOXES · ONE CAREFUL CAPTAIN',title:'Cargo Dock.',intro:'A little patience. A well-placed nudge.',steps:['Push each crate into the berth with its matching shape: circle, triangle, or square.','Go around to the back of a crate and gently push with your bow.','The entire crate must settle in its berth for one second. Wrong berth? Push it back out.','Reset cargo restarts the boat, boxes, and timer.'],start:'Start delivery'},lighthouse:{tag:'FOLLOW THE CLUE · LIGHT THE COAST',title:'Lighthouse Link.',intro:'Three little lights. One bright coastline.',steps:['Keep the symbol sequence in view as you explore the northern waterway.','Approach a matching navigation light and press F or Activate.','Light all three in order. A wrong choice clears progress; your clue stays the same.','Take your time. This voyage has no clock.'],start:'Start linking'}};
function openGames(){showPanel(`<span class="eyebrow">TAKE A LITTLE DETOUR</span><h2 class="panel-hero" id="panel-title">Play in the bay.</h2><p class="panel-summary">Three ways to get wonderfully sidetracked.</p>${challenges.map(c=>`<button class="directory-card" data-challenge="${c.id}"><span class="arrow">↗</span><small>${c.eyebrow}</small><h3>${c.name}</h3><p>${gameCopy[c.id].intro}</p></button>`).join('')}`,{id:'games'});}
function openChallenge(id){const c=gameCopy[id];if(!c)return;showPanel(`<span class="eyebrow">${c.tag}</span><h2 class="panel-hero" id="panel-title">${c.title}</h2><p class="panel-summary">${c.intro}</p><section class="panel-section"><h3>Your little mission</h3><ul>${c.steps.map(s=>`<li>${s}</li>`).join('')}</ul></section>${store.best(id)?`<p class="eyebrow">YOUR BEST</p><div class="race-result">${formatTime(store.best(id))}</div>`:''}<div class="panel-links"><button class="primary-button" data-start="${id}" ${!game?'disabled':''}>${c.start} ↗</button></div><p class="panel-footnote">${game?.challenges.active?'Starting this challenge ends your current round. ':''}Reading and menus pause the game. Docking, Reset, or Travel here ends the round. All records stay in this browser.</p>`,{id:'challenge-'+id});}
async function transition(action){if(!game)return;const token=++travelToken;closePanel({resume:false});game.cancelChallenge();game.pause('travel');$('#travel-fade').classList.add('active');await new Promise(r=>setTimeout(r,180));if(token!==travelToken)return;action();$('.intro').classList.add('compact');$('#travel-fade').classList.remove('active');$('#world').focus();}
async function travel(id){const i=islands.find(i=>i.id===id);if(i)await transition(()=>{game.teleport({...i.dock,yaw:i.yaw});toast(`Welcome to ${i.name}. E to read · F to play.`);});}
async function startChallenge(id){if(gameCopy[id])await transition(()=>game.startChallenge(id));}
function finished({kind,elapsed,best}){sound('finish');showPanel(`<span class="eyebrow">A NEW CHAPTER IN YOUR LOGBOOK</span><h2 class="panel-hero" id="panel-title">${kind==='lighthouse'?'You lit up the coast.':kind==='cargo'?'All neatly docked.':'Beautifully sailed.'}</h2>${kind==='lighthouse'?'<div class="celebration-symbol">✦</div><p class="panel-summary">Three lights linked. One happy little lighthouse.</p>':`<div class="race-result">${formatTime(elapsed)}</div><p class="panel-summary">Personal best: <strong>${formatTime(best)}</strong></p>`}<div class="panel-links"><button class="primary-button" data-start="${kind}">${kind==='buoy'?'Race again':'Play again'} ↗</button><button class="secondary-button" data-close>Back to exploring</button></div>`,{id:'result'});}
function openLogbook(tab='stamps'){if(tab==='sea'){showPanel(`<span class="eyebrow">LIFE AROUND THE ISLANDS</span><h2 class="panel-hero" id="panel-title">Sea Life.</h2><div class="directory-groups"><button data-logtab="stamps">Voyage stamps</button><button class="active" data-logtab="sea">Sea Life</button></div><p class="panel-summary">${store.seaLife.size} of 4 neighbours spotted. Take the scenic route.</p>${SEA_LIFE.map(a=>`<article class="sea-life-card ${store.seaLife.has(a.id)?'spotted':''}"><b>${a.icon}</b><div><h3>${a.name}</h3><p>${store.seaLife.has(a.id)?'Spotted ✓':a.hint}</p></div></article>`).join('')}<p class="panel-footnote">Keep an animal in view for a moment to record your sighting. Sea Life is separate from your 18 voyage stamps.</p><button class="text-link" id="clear-sealife">Clear Sea Life sightings</button>`,{id:'sealife'});return;}showPanel(`<span class="eyebrow">A VOYAGE TO REMEMBER</span><h2 class="panel-hero" id="panel-title">Captain’s logbook.</h2><div class="directory-groups"><button class="active" data-logtab="stamps">Voyage stamps</button><button data-logtab="sea">Sea Life</button></div><p class="panel-summary">${store.stamps} of 18 stamps collected. There’s no rush.</p><section class="panel-section"><h3>Island visits <span>${store.visited.size} / 9</span></h3><div class="stamp-grid">${islands.map(i=>`<button class="stamp ${store.visited.has(i.id)?'earned':''}" data-map-id="${i.id}"><b>${String(i.n).padStart(2,'0')}</b><strong>${esc(i.name)}</strong><small>${store.visited.has(i.id)?'Visited ✓':store.discovered.has(i.id)?'Discovered':'Sail by to discover'}${store.viewed.has(i.id)?' · Viewed':''}</small></button>`).join('')}</div><p class="panel-footnote">Sail close to discover an island. Spend a moment at its dock to collect its visit stamp. Reading from the directory only marks it Viewed.</p></section><section class="panel-section"><h3>Little discoveries <span>${store.secrets.size} / 6</span></h3>${SECRETS.map(s=>`<div class="secret-card ${store.secrets.has(s.id)?'earned':''}"><b>${store.secrets.has(s.id)?s.icon:'?'}</b><div><strong>${store.secrets.has(s.id)?s.title:'A little secret'}</strong><p>${store.secrets.has(s.id)?'Discovered ✓':s.hint}</p></div></div>`).join('')}</section><section class="panel-section"><h3>Playful detours <span>${store.completed.size} / 3</span></h3>${challenges.map(c=>`<button class="directory-card" data-challenge="${c.id}"><small>${store.completed.has(c.id)?'COMPLETED ✓':'WAITING FOR A CAPTAIN'}</small><h3>${c.name}</h3>${store.best(c.id)?`<p>Best · ${formatTime(store.best(c.id))}</p>`:''}</button>`).join('')}</section>`,{id:'logbook'});}
function openStudio(){if(!game)return;showPanel(`<span class="eyebrow">JACK’S BOAT STUDIO</span><h2 class="panel-hero" id="panel-title">Make it yours.</h2><p class="panel-summary">Three finishes. One little escape.</p><div class="livery-list">${LIVERIES.map(l=>`<button class="livery-card" data-livery="${l.id}" aria-pressed="${settings.livery===l.id}"><span class="livery-colours" aria-hidden="true">${l.swatches.map(c=>`<i style="background:${c}"></i>`).join('')}</span><span><strong>${l.name}</strong><small>${l.description}</small></span><span class="livery-check">✓</span></button>`).join('')}</div><p id="livery-status" class="studio-status" aria-live="polite">${LIVERIES.find(l=>l.id===settings.livery)?.name} · saved for your next voyage</p><button class="primary-button" data-close>Back to the bay ↗</button>`,{id:'studio',focus:{boatStudio:true}});}
function toggleSound(value=!settings.sound){settings.sound=value;store.save();$('#sound-button').setAttribute('aria-pressed',String(value));$('#sound-button').setAttribute('aria-label',value?'Disable sound':'Enable sound');$('#sound-button').innerHTML=value?'♫':'♫<span class="slash"></span>';if(value)sound();}
function syncZoom(){$('#zoom-label').textContent=ZOOM_NAMES[settings.zoom];$('#zoom-in').disabled=settings.zoom===0;$('#zoom-out').disabled=settings.zoom===2;}
function openSettings(){showPanel(`<span class="eyebrow">MAKE YOURSELF AT HOME</span><h2 class="panel-hero" id="panel-title">Smooth sailing.</h2><label class="setting-row"><span>Sound<small>Splashes, bells, and a gentle engine</small></span><input id="setting-sound" type="checkbox" ${settings.sound?'checked':''}></label><label class="setting-row"><span>Visual quality<small>Low uses fewer effects and less power</small></span><select id="setting-quality"><option value="high" ${settings.quality==='high'?'selected':''}>High</option><option value="low" ${settings.quality==='low'?'selected':''}>Low</option></select></label><label class="setting-row"><span>Reduce motion<small>A steady boat and wider, fixed view</small></span><input id="setting-motion" type="checkbox" ${settings.reduced?'checked':''}></label><label class="setting-row"><span>Camera distance<small>Automatically widens for safe sailing</small></span><select id="setting-zoom">${ZOOM_NAMES.map((n,i)=>`<option value="${i}" ${settings.zoom===i?'selected':''}>${n}</option>`).join('')}</select></label><button class="studio-entry" data-studio>Customize boat <span>Three signature finishes ↗</span></button><section class="panel-section"><h3>At the helm</h3><p class="panel-summary">W / ↑: throttle · S / ↓: reverse<br>A D / ← →: steer<br>Shift: boost · Space: brake<br>E / Enter: read · F: play · H: horn<br>M: map · R: reset · Escape: close</p></section><div class="panel-links"><button class="secondary-button" id="reading-mode">Browse without 3D ↗</button><button class="text-link" id="clear-logbook">Clear exploration stamps</button></div><p class="panel-footnote">Clearing stamps keeps your settings and best times. Records stay in this browser.</p>`,{id:'settings'});}
function dock(){if(game?.nearby&&!$('#panel').open)openEntry(game.nearby.id,{dock:true});}
$('#panel-close').onclick=()=>closePanel();$('#panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;const d=b.dataset;if('studio'in d)openStudio();else if(d.livery){game?.setLivery(d.livery);for(const card of document.querySelectorAll('[data-livery]'))card.setAttribute('aria-pressed',String(card.dataset.livery===settings.livery));$('#livery-status').textContent=LIVERIES.find(l=>l.id===settings.livery).name+' · saved for your next voyage';}else if(d.logtab)openLogbook(d.logtab);else if(b.id==='clear-sealife'){store.clearSeaLife();openLogbook('sea');}else if(d.open)openEntry(d.open);else if(d.category)openDirectory(d.category);else if(d.travel)travel(d.travel);else if(d.mapId)openMap(d.mapId);else if(d.challenge)openChallenge(d.challenge);else if(d.start)startChallenge(d.start);else if('logbook'in d)openLogbook();else if('close'in d)closePanel();else if(b.id==='reading-mode'){closePanel({resume:false});enableFallback(false);}else if(b.id==='clear-logbook'){store.clearLogbook();toast('Exploration stamps cleared. A fresh voyage awaits.');}else if(b.classList.contains('brand')){e.preventDefault();openEntry('harbor');}});
document.addEventListener('change',e=>{if(e.target.id==='setting-sound')toggleSound(e.target.checked);if(e.target.id==='setting-quality'){settings.quality=e.target.value;game?.setQuality(settings.quality);}if(e.target.id==='setting-motion'){settings.reduced=e.target.checked;document.body.classList.toggle('reduced',settings.reduced);}if(e.target.id==='setting-zoom'){settings.zoom=Number(e.target.value);game?.setZoom(settings.zoom);syncZoom();}store.save();});
$('#browse-button').onclick=()=>openDirectory();$('#mobile-menu').onclick=()=>openDirectory();$('#minimap-button').onclick=()=>openMap();$('#settings-button').onclick=openSettings;$('#sound-button').onclick=()=>toggleSound();$('#games-button').onclick=openGames;$('#logbook-button').onclick=openLogbook;$('#mobile-logbook').onclick=openLogbook;
$('#helm-button').onclick=()=>{$('.intro').classList.add('compact');$('#world').focus();toast(matchMedia('(pointer:coarse)').matches?'Use the left joystick to steer. E / Read opens an island.':'WASD to sail · E to read · F to play.');};
$('#horn-button').onclick=()=>game?.horn();
$('#dock-button').onclick=dock;$('#play-button').onclick=()=>game?.interact();$('#zoom-in').onclick=()=>game?.setZoom(settings.zoom-1);$('#zoom-out').onclick=()=>game?.setZoom(settings.zoom+1);
function reset(){if(game){const i=game.reset();toast(`Back in safe water near ${i.name}.`);}}
$('#reset-button').onclick=reset;$('#touch-reset').onclick=reset;$('#cargo-reset').onclick=()=>startChallenge('cargo');$('#challenge-exit').onclick=()=>{game?.cancelChallenge();inputs.setEnabled(true);toast('Round ended. There’s more to explore.');};
inputs.events.on('action',key=>{if(key==='KeyM')openMap();if(key==='KeyE'||key==='Enter')dock();if(key==='KeyF')game?.interact();if(key==='KeyR')reset();if(key==='KeyH')game?.horn();});
function background(){if(game?.boat){visibilityPaused=true;game.pause('hidden',game.focus);inputs.clear();audio?.suspend();}}
function foreground(){if(game?.boat&&visibilityPaused&&!document.hidden&&!$('#panel').open){visibilityPaused=false;game.resume();}}
document.addEventListener('visibilitychange',()=>document.hidden?background():foreground());window.addEventListener('blur',background);window.addEventListener('focus',foreground);
const mini=$('#minimap'),ctx=mini.getContext('2d');function drawMap(p={x:0,z:67},yaw=0){const w=mini.width,h=mini.height,s=.85,sz=.76;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#94c5ba';ctx.setLineDash([4,6]);ctx.beginPath();ctx.ellipse(w/2,h/2,174*s,174*sz,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(const i of islands){ctx.beginPath();i.shore.forEach(([x,z],n)=>{const q=toWorld(i,x,z);n?ctx.lineTo(w/2+q.x*s,h/2+q.z*sz):ctx.moveTo(w/2+q.x*s,h/2+q.z*sz);});ctx.closePath();ctx.fillStyle=store.visited.has(i.id)?'#d09b62':'#83a78c';ctx.fill();ctx.fillStyle='#fffaf0';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(String(i.n),w/2+i.x*s,h/2+i.z*sz+4);}for(const c of challenges){ctx.fillStyle='#f29157';ctx.beginPath();ctx.arc(w/2+c.x*s,h/2+c.z*sz,3,0,7);ctx.fill();}if(game?.challenges.kind==='buoy'&&game.challenges.active){ctx.strokeStyle='#df945a';ctx.setLineDash([4,4]);ctx.beginPath();gates.forEach((g,n)=>n?ctx.lineTo(w/2+g.x*s,h/2+g.z*sz):ctx.moveTo(w/2+g.x*s,h/2+g.z*sz));ctx.stroke();ctx.setLineDash([]);}if(game?.challenges.kind==='lighthouse'&&game.challenges.active){for(const l of lamps){ctx.fillStyle='#294f5d';ctx.font='bold 16px sans-serif';ctx.fillText(l.symbol,w/2+l.x*s,h/2+l.z*sz);}}if(game?.challenges.kind==='cargo'&&game.challenges.active){for(const b of game.challenges.berths){ctx.fillStyle=b.color;ctx.fillRect(w/2+b.x*s-3,h/2+b.z*sz-2,6,4);}}ctx.save();ctx.translate(w/2+p.x*s,h/2+p.z*sz);ctx.rotate(-yaw);ctx.fillStyle='#ee7747';ctx.strokeStyle='#fffdf5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(6,6);ctx.lineTo(0,3);ctx.lineTo(-6,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
let lastUI=0,boundaryWarned=false;function frame({position,yaw,speed,now,frozen}){if(speed>1)$('.intro').classList.add('compact');if(now-lastUI<70)return;lastUI=now;drawMap(position,yaw);const boundary=Math.hypot(position.x,position.z)>WORLD_RADIUS-12;if(boundary&&!boundaryWarned)toast('Open water ahead. Turn back toward the islands.');boundaryWarned=boundary;
 const labels=islands.map(i=>({i,p:game.project({x:i.x,y:9,z:i.z}),d:Math.hypot(position.x-i.x,position.z-i.z)})).filter(({p,d})=>p.z<1&&Math.abs(p.x)<.82&&p.y>-.35&&p.y<.75&&d<70).sort((a,b)=>a.d-b.d).slice(0,2);for(const i of islands){const n=$(`[data-label="${i.id}"]`),l=labels.find(l=>l.i.id===i.id);n.style.opacity=l&&!$('#panel').open?'1':'0';if(l){n.style.left=`${(l.p.x*.5+.5)*innerWidth}px`;n.style.top=`${(-l.p.y*.5+.5)*innerHeight}px`;}}
 $('#horn-button').disabled=frozen||!!$('#panel').open||(game.fleet&&game.fleet.time-game.fleet.lastHorn<3);
 const available=!frozen&&!$('#panel').open;$('#dock-button').hidden=!available||!game.nearby;$('#play-button').hidden=!available||!game.nearAction;if(game.nearby)$('#dock-copy').textContent=`Read ${game.nearby.name}`;if(game.nearAction)$('#play-copy').textContent=game.nearAction.label;
 const c=game.challenges;$('#challenge-hud').hidden=!c.active;$('#cargo-reset').hidden=c.kind!=='cargo';if(c.active){$('#challenge-name').textContent=challenges.find(x=>x.id===c.kind).name;$('#challenge-time').textContent=c.kind==='lighthouse'?'Light the coast':formatTime(c.elapsed);$('#challenge-progress').textContent=`${c.index} / ${c.kind==='buoy'?6:3} ${c.kind==='buoy'?'gates':c.kind==='cargo'?'crates':'lights'}`;if(c.kind==='buoy'){const g=gates[c.index];if(g){const d=Math.atan2(g.x-position.x,-(g.z-position.z))+game.cameraRig.yaw;$('#challenge-guide').innerHTML=`<b style="display:inline-block;transform:rotate(${d}rad)">↑</b> Gate ${c.index+1} · ${Math.round(Math.hypot(g.x-position.x,g.z-position.z))} m`;}}else if(c.kind==='lighthouse')$('#challenge-guide').innerHTML=`<div class="clue-row">${c.sequence.map((id,n)=>{const l=lamps.find(l=>l.id===id);return `<span class="${n<c.index?'lit':''}">${l.symbol} ${l.name}${n<c.index?' ✓':''}</span>`;}).join('<i>→</i>')}</div>${lamps.find(l=>l.id===c.sequence[c.index])?bearing(lamps.find(l=>l.id===c.sequence[c.index]),position):''}`;else $('#challenge-guide').textContent='● Circle   ·   ▲ Triangle   ·   ■ Square';}
 const countdown=['countdown','resuming'].includes(c.state)&&game.mode==='exploring';$('#countdown').hidden=!countdown;if(countdown)$('#countdown').textContent=Math.max(1,Math.ceil((c.deadline-performance.now())/1000));
 if(settings.sound&&audio){try{if(!engine){const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.connect(gain).connect(audio.destination);gain.gain.value=0;osc.start();engine={osc,gain};}engine.osc.frequency.setTargetAtTime(48+speed*4,audio.currentTime,.15);engine.gain.gain.setTargetAtTime(frozen?0:Math.min(speed*.0014,.022),audio.currentTime,.2);}catch{}}else if(engine)engine.gain.gain.setTargetAtTime(0,audio.currentTime,.1);
}
function enableFallback(failed=true){inputs.setEnabled(false);document.body.classList.add('no-3d');$('#loading').hidden=true;$('#fallback').hidden=false;$('#fallback-cards').innerHTML=content.map(card).join('');$('.intro').classList.remove('compact');if(game){if(game.boat){game.pause('reading');fallbackGame=failed?null:game;}game.renderer?.setAnimationLoop(null);game=null;}$('#back-to-sea').textContent=fallbackGame?'Back to the sea ↗':'Try the sea again ↗';if(failed)toast('The sea is taking a break. Every island is still here to explore.');}
$('#back-to-sea').onclick=()=>{if(fallbackGame){game=fallbackGame;fallbackGame=null;document.body.classList.remove('no-3d');$('#fallback').hidden=true;game.resume();game.renderer.setAnimationLoop(()=>game.safeFrame());}else location.href=location.pathname;};
$('#stamp-count').textContent=`${store.stamps} / 18`;document.body.classList.toggle('reduced',settings.reduced);syncZoom();drawMap();toggleSound(settings.sound);$('#island-labels').innerHTML=islands.map(i=>`<div class="island-label" data-label="${i.id}" style="opacity:0"><span class="number">${String(i.n).padStart(2,'0')}</span>${esc(i.name)}</div>`).join('');
async function boot(){if(new URLSearchParams(location.search).has('no3d')){enableFallback(false);return;}try{const {Game}=await import('./game.js');game=new Game($('#world'),inputs,settings,store);game.events.on('failure',error=>{console.error('Sea rendering stopped:',error);enableFallback();});game.events.on('ready',renderer=>{$('#loading').hidden=true;document.body.dataset.renderer=renderer;});game.events.on('asset',({count})=>$('#loading-copy').textContent=`Preparing your boat… ${Math.min(95,Math.round(count/3*90))}%`);game.events.on('frame',frame);game.events.on('finish',finished);game.events.on('challengeopen',openChallenge);game.events.on('message',toast);game.events.on('zoom',syncZoom);game.events.on('sound',({kind,strength})=>sound(kind,strength));game.events.on('discovery',id=>toast(`Discovered · ${SECRETS.find(s=>s.id===id).title}`));game.events.on('split',e=>toast(`Gate ${e.index} ✓ · Split ${formatTime(e.split)}`));game.events.on('rescue',reset);await game.init();if($('#panel').open)game.pause('read');$('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();enableFallback();});}catch(error){console.error('3D initialization:',error);enableFallback();}}
boot();
registerVoyageTools({islands,read:openEntry,travel,close:closePanel,play:startChallenge,interact:()=>game?.interact(),dock,steer:async(input,duration)=>{if(game?.mode!=='exploring')throw new Error('Close the panel before sailing.');await inputs.steerFor(input,duration);},status:()=>({...game?.status(),available3D:!!game?.boat,panel:currentId,logbook:{visited:[...store.visited],viewed:[...store.viewed],discovered:[...store.discovered],secrets:[...store.secrets],completed:[...store.completed]},islands:islands.map(i=>({id:i.id,name:i.name}))})});
