// Build only the owner-provided Raptor. Does not install or alter other vehicles.
// node build-raptor.mjs --project /path/to/site --source /path/Ford-raptor.glb --output /tmp/raptor-assets [--rig /path/fit.json]
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const args=new Map();for(let i=2;i<process.argv.length;i+=2)args.set(process.argv[i],process.argv[i+1]);
const project=path.resolve(args.get('--project')||process.cwd()),source=args.get('--source'),output=path.resolve(args.get('--output')||path.join(project,'.asset-build/raptor')),targetLength=Number(args.get('--length')||5.2);
if(!source)throw Error('Provide --source Ford-raptor.glb.');
const require=createRequire(path.join(project,'package.json'));
const {NodeIO}=require('@gltf-transform/core'),{ALL_EXTENSIONS}=require('@gltf-transform/extensions'),{weld,simplify,prune,meshopt}=require('@gltf-transform/functions'),{MeshoptEncoder,MeshoptDecoder,MeshoptSimplifier}=require('meshoptimizer');
await Promise.all([MeshoptEncoder.ready,MeshoptDecoder.ready,MeshoptSimplifier.ready]);
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});
await fs.mkdir(path.join(output,'low'),{recursive:true});await fs.mkdir(path.join(output,'source-rigged'),{recursive:true});
function bounds(p,ids){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const id of ids)for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[id*3+k]);max[k]=Math.max(max[k],p[id*3+k]);}return {min,max,size:max.map((x,k)=>x-min[k]),center:max.map((x,k)=>(x+min[k])/2)};}
function components(p,index){const n=p.length/3,parent=Int32Array.from({length:n},(_,i)=>i),rank=new Uint8Array(n),find=x=>{while(parent[x]!==x){parent[x]=parent[parent[x]];x=parent[x];}return x;},join=(a,b)=>{a=find(a);b=find(b);if(a===b)return;if(rank[a]<rank[b])[a,b]=[b,a];parent[b]=a;if(rank[a]===rank[b])rank[a]++;};for(let i=0;i<index.length;i+=3){join(index[i],index[i+1]);join(index[i],index[i+2]);}const seen=new Map();for(let i=0;i<n;i++){const key=p[i*3]+','+p[i*3+1]+','+p[i*3+2];if(seen.has(key))join(i,seen.get(key));else seen.set(key,i);}const groups=new Map();for(let i=0;i<index.length;i+=3){const r=find(index[i]);if(!groups.has(r))groups.set(r,[]);groups.get(r).push(index[i],index[i+1],index[i+2]);}return [...groups.values()].sort((a,b)=>b.length-a.length);}
function smoothSeamNormals(doc){for(const mesh of doc.getRoot().listMeshes())for(const prim of mesh.listPrimitives()){const p=prim.getAttribute('POSITION').getArray(),n=prim.getAttribute('NORMAL').getArray(),sum=new Map();for(let i=0;i<p.length;i+=3){const key=p[i]+','+p[i+1]+','+p[i+2],v=sum.get(key)||[0,0,0];for(let k=0;k<3;k++)v[k]+=n[i+k];sum.set(key,v);}for(let i=0;i<p.length;i+=3){const v=sum.get(p[i]+','+p[i+1]+','+p[i+2]),len=Math.hypot(...v)||1;for(let k=0;k<3;k++)n[i+k]=v[k]/len;}}}
const triangleCount=doc=>doc.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).reduce((n,p)=>n+p.getIndices().getCount()/3,0);
const doc=await io.read(source),root=doc.getRoot(),scene=root.listScenes()[0],originalNode=root.listNodes().find(n=>n.getMesh()),originalMesh=originalNode.getMesh(),original=originalMesh.listPrimitives()[0],buffer=root.listBuffers()[0],material=original.getMaterial(),p=original.getAttribute('POSITION').getArray(),normal=original.getAttribute('NORMAL').getArray(),uv=original.getAttribute('TEXCOORD_0').getArray(),indices=original.getIndices().getArray(),b=bounds(p,indices),scale=targetLength/b.size[2],origin=[b.center[0],b.min[1],b.center[2]],map=v=>[-(v[0]-origin[0])*scale,(v[1]-origin[1])*scale,-(v[2]-origin[2])*scale];
const groups=components(p,indices);if(groups.length!==5)throw Error(`Expected exact body + four wheels, found ${groups.length}.`);
const parts=new Map(),sourceWheelBounds={},sourceWheelCenters={},wheelCenters={},wheelRadii={},wheelEnvelopes={};
parts.set('car-body',groups[0]);for(const ids of groups.slice(1)){const wb=bounds(p,ids),name=`car-wheel-${wb.center[2]>0?'front':'rear'}-${wb.center[0]>0?'left':'right'}`,c=wb.center;parts.set(name,ids);sourceWheelBounds[name]=wb;sourceWheelCenters[name]=c;wheelCenters[name]=map(c);let maxR=0;for(const id of ids)maxR=Math.max(maxR,Math.hypot(p[id*3+1]-c[1],p[id*3+2]-c[2]));wheelRadii[name]=maxR*scale;wheelEnvelopes[name]={radius:maxR*scale,minRestY:wb.min[1]*scale,fullSpinMinY:(c[1]-maxR)*scale,sourceCenter:c,sourceBounds:wb};}
// The largest connected surface inside this cabin-only mask is the driver
// chair (including its complete cushion and headrest). Other components are
// pillar trim; keep them fixed with the body. The cut base is below the floor
// after the approved seat lowering, while all source triangles are retained.
const seatROI=[];
for(let i=0;i<groups[0].length;i+=3){const ids=groups[0].slice(i,i+3);if(ids.every(id=>p[id*3]>.030&&p[id*3]<.130&&p[id*3+1]>.182&&p[id*3+1]<.345&&p[id*3+2]>-.012&&p[id*3+2]<.164&&(p[id*3+2]<.105||p[id*3+1]<.224)&&(p[id*3+2]>.015||p[id*3+1]>.22)))seatROI.push(...ids);}
const seatComponents=components(p,seatROI),seatTriangles=seatComponents[0],seatSet=new Set();
if(seatTriangles.length/3!==34355)throw Error('Unexpected source driver chair topology.');
for(let i=0;i<seatTriangles.length;i+=3)seatSet.add(seatTriangles.slice(i,i+3).join(','));
const body=[],roof=[],seat=[];
for(let i=0;i<groups[0].length;i+=3){const ids=groups[0].slice(i,i+3),onRoof=ids.every(id=>p[id*3+1]>.350&&Math.abs(p[id*3])<.203&&p[id*3+2]>-.16&&p[id*3+2]<.195),onSeat=seatSet.has(ids.join(','));(onRoof?roof:onSeat?seat:body).push(...ids);}
parts.set('car-body',body);parts.set('car-roof',roof);parts.set('car-driver-seat',seat);
if([...parts.values()].reduce((n,x)=>n+x.length,0)!==indices.length)throw Error('Source triangle partition changed geometry.');
const seatSurface=map([.09,.19784157077,.10]),steeringCenter=map([.09,.260,.151]),pelvis=[seatSurface[0],seatSurface[1]+.035,seatSurface[2]],grips={Left:[steeringCenter[0]-.165,steeringCenter[1],steeringCenter[2]],Right:[steeringCenter[0]+.165,steeringCenter[1],steeringCenter[2]]},feet={Left:[pelvis[0]-.11,pelvis[1]-.21,pelvis[2]-.15],Right:[pelvis[0]+.11,pelvis[1]-.21,pelvis[2]-.15]};
const rig={id:'raptor',label:'Ford Raptor',forward:[0,0,-1],up:[0,1,0],dimensions:b.size.map(v=>v*scale),sourceScale:scale,sourceLength:b.size[2],sourceTriangleCount:indices.length/3,partitionTriangleCounts:Object.fromEntries([...parts].map(([name,ids])=>[name,ids.length/3])),wheelNodes:Object.keys(wheelCenters),steerNodes:['car-steer-front-left','car-steer-front-right'],wheelCenters,wheelRadii,wheelRadius:Math.max(...Object.values(wheelRadii)),wheelEnvelopes,wheelRollAxis:[1,0,0],wheelRollSign:-1,steerAxis:[0,1,0],wheelbase:Math.abs(wheelCenters['car-wheel-front-left'][2]-wheelCenters['car-wheel-rear-left'][2]),trackWidth:Math.abs(wheelCenters['car-wheel-front-left'][0]-wheelCenters['car-wheel-front-right'][0]),wheelContactPoints:Object.fromEntries(Object.entries(wheelCenters).map(([name,c])=>[name,[c[0],0,c[2]]])),stableGroundLift:Math.max(0,...Object.values(wheelEnvelopes).map(e=>-e.fullSpinMinY)),wheelGrounding:'Use constant measured full-spin radius for chassis support; never follow individual tread lugs with per-frame vertical offsets.',seatSurface,steeringCenter,pelvis,grips,feet,torsoLean:.10,handPitch:1.1,seatDrop:.14,roofNode:'car-roof',roofCutawayNode:null,roofRetained:true,driverSeatNode:'car-driver-seat',sourceDriverSeatBounds:bounds(p,seat),driverSeatBounds:bounds(p,seat),sourceRoofBounds:bounds(p,roof),roofSourceInteriorY:[.3536,.3569],windshield:'Original open aperture; no opaque glass faces cover the front or driver side window.',seatContourSource:{x:.09,yz:[[.192297489,-.05],[.20255125,0],[.259223727,.05],[.197841571,.10],[.203041716,.15]],order:'[sourceY,sourceZ]'},fitStatus:'Initial source measured anchors; requires final posed Jack roof/headrest fit.'};
rig.driverSeatBounds={min:map([rig.sourceDriverSeatBounds.max[0],rig.sourceDriverSeatBounds.min[1],rig.sourceDriverSeatBounds.max[2]]),max:map([rig.sourceDriverSeatBounds.min[0],rig.sourceDriverSeatBounds.max[1],rig.sourceDriverSeatBounds.min[2]])};
const defaultFit=path.join(path.dirname(fileURLToPath(import.meta.url)),'raptor-rig.json');
const fitPath=args.get('--rig')||(await fs.access(defaultFit).then(()=>defaultFit,()=>null));
if(!fitPath)throw Error('Missing default raptor-rig.json beside this generator; provide --rig to select a measured fit.');
Object.assign(rig,JSON.parse(await fs.readFile(fitPath,'utf8')));
rig.driverSeatTranslation=[0,-rig.seatDrop,0];
rig.driverSeatBounds.min[1]-=rig.seatDrop;rig.driverSeatBounds.max[1]-=rig.seatDrop;
rig.contactTargets={pelvis:rig.pelvis,grips:rig.grips,feet:rig.feet,torsoLean:rig.torsoLean,handPitch:rig.handPitch,headPitch:rig.headPitch,footPitch:rig.footPitch};
const car=doc.createNode('car-raptor').setExtras({carRig:rig});scene.removeChild(originalNode);scene.addChild(car);
for(const [name,ids]of parts){const lookup=new Map(),vertices=[];for(const id of ids)if(!lookup.has(id)){lookup.set(id,vertices.length);vertices.push(id);}const pivot=sourceWheelCenters[name]?map(sourceWheelCenters[name]):[0,0,0],pos=new Float32Array(vertices.length*3),norm=new Float32Array(vertices.length*3),tex=new Float32Array(vertices.length*2);for(let i=0;i<vertices.length;i++){const id=vertices[i],point=map([p[id*3],p[id*3+1],p[id*3+2]]);for(let k=0;k<3;k++){pos[i*3+k]=point[k]-pivot[k];norm[i*3+k]=normal[id*3+k]*(k===1?1:-1);}tex[i*2]=uv[id*2];tex[i*2+1]=uv[id*2+1];}const prim=doc.createPrimitive().setMaterial(material).setAttribute('POSITION',doc.createAccessor(name+'-position',buffer).setType('VEC3').setArray(pos)).setAttribute('NORMAL',doc.createAccessor(name+'-normal',buffer).setType('VEC3').setArray(norm)).setAttribute('TEXCOORD_0',doc.createAccessor(name+'-uv',buffer).setType('VEC2').setArray(tex)).setIndices(doc.createAccessor(name+'-indices',buffer).setType('SCALAR').setArray(Uint32Array.from(ids,id=>lookup.get(id)))),mesh=doc.createMesh(name).addPrimitive(prim),node=doc.createNode(name).setExtras({carPart:name,sourceTriangles:ids.length/3});if(name.startsWith('car-wheel'))node.addChild(doc.createNode(name+'-surface').setMesh(mesh));else node.setMesh(mesh);if(name==='car-driver-seat')node.setTranslation(rig.driverSeatTranslation);if(name.startsWith('car-wheel-front')){const steer=doc.createNode(name.replace('wheel','steer')).setTranslation(pivot);steer.addChild(node);car.addChild(steer);}else{if(name!=='car-driver-seat')node.setTranslation(pivot);car.addChild(node);}}
for(const [name,position]of Object.entries({'car-anchor-seat':rig.seatSurface,'car-anchor-pelvis':rig.pelvis,'car-anchor-steering':rig.steeringCenter,'car-anchor-grip-left':rig.grips.Left,'car-anchor-grip-right':rig.grips.Right,'car-anchor-foot-left':rig.feet.Left,'car-anchor-foot-right':rig.feet.Right}))car.addChild(doc.createNode(name).setTranslation(position).setExtras({carAnchor:true}));
originalNode.dispose();originalMesh.dispose();await doc.transform(prune({keepLeaves:true}));const raw=path.join(output,'source-rigged/car-raptor.glb');await io.write(raw,doc);console.log('Source rig ready',raw);
function addFootrest(document){
  const support=rig.footrest;if(!support)return;
  const material=document.createMaterial('driver-footrest-rubber').setBaseColorFactor([.025,.03,.035,1]).setRoughnessFactor(.9).setMetallicFactor(0);
  const corners=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];
  const faces=[{ids:[1,2,6,5],n:[1,0,0]},{ids:[0,4,7,3],n:[-1,0,0]},{ids:[3,7,6,2],n:[0,1,0]},{ids:[0,1,5,4],n:[0,-1,0]},{ids:[4,5,6,7],n:[0,0,1]},{ids:[0,3,2,1],n:[0,0,-1]}];
  const positions=[],normals=[],indices=[];
  for(const face of faces){const first=positions.length/3;for(const id of face.ids){positions.push(...corners[id].map((v,k)=>(support.min[k]+support.max[k])/2+v*(support.max[k]-support.min[k])/2));normals.push(...face.n);}indices.push(first,first+1,first+2,first,first+2,first+3);}
  const buffer=document.getRoot().listBuffers()[0],prim=document.createPrimitive().setMaterial(material).setAttribute('POSITION',document.createAccessor('footrest-position',buffer).setType('VEC3').setArray(new Float32Array(positions))).setAttribute('NORMAL',document.createAccessor('footrest-normal',buffer).setType('VEC3').setArray(new Float32Array(normals))).setIndices(document.createAccessor('footrest-index',buffer).setType('SCALAR').setArray(new Uint16Array(indices)));
  document.getRoot().listNodes().find(n=>n.getName()==='car-raptor').addChild(document.createNode(support.name).setMesh(document.createMesh(support.name).addPrimitive(prim)).setExtras({carPart:'driver-footrest',addedSupport:true}));
}
const entry={id:'raptor',source:path.basename(source),sourceSHA256:createHash('sha256').update(await fs.readFile(source)).digest('hex'),sourceBytes:(await fs.stat(source)).size,rig,variants:{}};
for(const quality of ['high','low']){const d=await io.read(raw),target=quality==='high'?112000:42000,max=quality==='high'?120000:45000;smoothSeamNormals(d);await d.transform(weld(),simplify({simplifier:MeshoptSimplifier,ratio:target/(indices.length/3),error:quality==='high'?.008:.02}),prune({keepLeaves:true}));let count=triangleCount(d);if(count>max){await d.transform(simplify({simplifier:MeshoptSimplifier,ratio:target/count,error:quality==='high'?.018:.04}),prune({keepLeaves:true}));count=triangleCount(d);}if(count>max)throw Error(`Triangle limit exceeded: ${quality} ${count}`);if(quality==='low')for(const texture of d.getRoot().listTextures()){const file=path.join(output,texture.getName()+'-low.jpg');await fs.writeFile(file,texture.getImage());const process=spawnSync('sips',['-Z','1024',file,'--out',file],{encoding:'utf8'});if(process.status)throw Error(process.stderr);texture.setImage(new Uint8Array(await fs.readFile(file)));await fs.unlink(file);}addFootrest(d);await d.transform(meshopt({encoder:MeshoptEncoder,level:'high'}));const file=path.join(output,quality==='low'?'low':'','car-raptor.glb');await io.write(file,d);const checked=await io.read(file);entry.variants[quality]={file:path.relative(output,file),bytes:(await fs.stat(file)).size,triangles:triangleCount(checked),textures:checked.getRoot().listTextures().map(t=>({name:t.getName(),size:t.getSize(),bytes:t.getImage().length})),meshNames:checked.getRoot().listNodes().filter(n=>n.getMesh()).map(n=>n.getName())};console.log(quality,entry.variants[quality]);}
await fs.writeFile(path.join(output,'manifest.json'),JSON.stringify({version:1,coordinateSystem:'Meters; Y up, front -Z, driver -X; original full roof always retained.',models:[entry]},null,2)+'\n');console.log('Finished Raptor only',output);
