import * as THREE from 'three';
import {islands,toWorld} from '../config.js';
import {dockDistance} from '../core/dock.js';
import {oceanHeight} from './water-space.js';
export class IslandDetails{
 constructor(scene,settings,loader){Object.assign(this,{scene,settings,loader});this.items=new Map();this.dummy=new THREE.Object3D();
  this.fenders=new THREE.InstancedMesh(new THREE.CapsuleGeometry(.12,.42,3,7),new THREE.MeshStandardMaterial({color:'#eee4cb',roughness:.8}),18);this.lines=new THREE.InstancedMesh(new THREE.CylinderGeometry(.018,.018,.42,5),new THREE.MeshStandardMaterial({color:'#aa946c'}),18);this.ripples=new THREE.InstancedMesh(new THREE.RingGeometry(.36,.39,20),new THREE.MeshBasicMaterial({color:'#e5f3db',transparent:true,opacity:.4,depthWrite:false,side:THREE.DoubleSide}),18);this.mist=new THREE.InstancedMesh(new THREE.SphereGeometry(.075,5,4),new THREE.MeshBasicMaterial({color:'#d9f2e5',transparent:true,opacity:.28,depthWrite:false}),24);this.mist.frustumCulled=false;scene.add(this.mist);for(const m of [this.fenders,this.lines,this.ripples]){m.frustumCulled=false;scene.add(m);}
 }
 async ensure(island){const quality=this.settings.quality;let item=this.items.get(island.id);if(!item){item={island,cache:new Map(),pending:new Set(),model:null};this.items.set(island.id,item);}if(item.cache.has(quality)){this.show(item,quality);return;}if(item.pending.has(quality))return;item.pending.add(quality);
  try{const model=(await this.loader.loadAsync(`/models/details/${quality==='low'?'low/':''}${island.id}.glb`)).scene;model.position.set(island.x,0,island.z);model.rotation.y=island.rotation;model.traverse(o=>{if(o.isMesh){o.castShadow=quality==='high';o.receiveShadow=true;}});item.cache.set(quality,model);model.userData.chime=model.getObjectByName('anim_detail_chime');this.scene.add(model);if(this.settings.quality===quality)this.show(item,quality);else model.visible=false;}catch(e){console.warn('Island details unavailable',island.id,e.message);}finally{item.pending.delete(quality);}
 }
 show(item,quality){for(const [q,m]of item.cache)m.visible=q===quality;item.model=item.cache.get(quality);}
 update(dt,p,time,waterTime,controllers){let n=0;for(const island of islands){const distance=Math.hypot(p.x-island.x,p.z-island.z),item=this.items.get(island.id);if(distance<65&&(!item||!item.cache.has(this.settings.quality)))this.ensure(island);if(item?.model){item.model.visible=distance<90;const node=item.model.userData.chime;if(node){const controller=controllers.get(island.id),active=controller?.elapsed<controller?.duration;node.rotation.z=this.settings.reduced?0:Math.sin(time*(active?5:2.1))*(active?.20:.045);}}
   const near=dockDistance(p,island)<6;for(const side of [-1,1]){const q=toWorld(island,side*1.68,12.4),sway=!this.settings.reduced&&near?Math.sin(time*3)*.1:0;this.dummy.position.set(q.x,.34,q.z);this.dummy.rotation.set(sway,0,side*.08);this.dummy.scale.setScalar(distance<65?1:0);this.dummy.updateMatrix();this.fenders.setMatrixAt(n,this.dummy.matrix);
    this.dummy.position.y=.76;this.dummy.scale.setScalar(distance<65?1:0);this.dummy.updateMatrix();this.lines.setMatrixAt(n,this.dummy.matrix);
    const radius=.8+(Math.sin(time*1.7+n)*.5+.5)*.65;this.dummy.position.y=oceanHeight(q.x,q.z,waterTime)+.02;this.dummy.rotation.set(-Math.PI/2,0,0);this.dummy.scale.setScalar(distance<65?radius:0);this.dummy.updateMatrix();this.ripples.setMatrixAt(n++,this.dummy.matrix);}
  }const garden=islands.find(i=>i.id==='visionx'),controller=controllers.get('visionx'),active=controller?.elapsed<controller?.duration&&!this.settings.reduced&&Math.hypot(p.x-garden.x,p.z-garden.z)<65;
  for(let n=0;n<24;n++){const age=(time*1.2+n/24)%1,a=n*2.399+time*.3,q=toWorld(garden,4.4+Math.cos(a)*age*1.6,4+Math.sin(a)*age*.8);this.dummy.position.set(q.x,1.7+Math.sin(age*Math.PI)*.5-age*.6,q.z);this.dummy.rotation.set(0,0,0);this.dummy.scale.setScalar(active&&(this.settings.quality==='high'||n%2===0)?Math.sin(age*Math.PI)*1.5:0);this.dummy.updateMatrix();this.mist.setMatrixAt(n,this.dummy.matrix);}this.mist.instanceMatrix.needsUpdate=true;for(const m of [this.fenders,this.lines,this.ripples])m.instanceMatrix.needsUpdate=true;
 }
 setQuality(){for(const item of this.items.values())this.ensure(item.island);}
}
